
public class DDSettlementTemplate {

	  public static final String OutDDSettlementHeader = 
			  
		 "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
		+"\n<MeridianMessage MessageType=\"ISO20022_MPM"+"\nDebit\" MessageFormat=\"StandardXML\" System=\"ISO20022\">"
		+"\n	<CustomerID>1</CustomerID>"
		+"\n	<MeridianMessageType>ISO20022_MPM"+"\nDebit</MeridianMessageType>"
		+"\n	<ExternalMessageType>MPM"+"\nDebit</ExternalMessageType>"
		+"\n	<InternalMessageType>P</InternalMessageType>"
		+"\n	<HostID>MPM</HostID>"
		+"\n	<Direction>O</Direction>"
		+"\n	<ValueDate>20161201</ValueDate>"
		+"\n	<CurrencyCode>EUR</CurrencyCode>"
		+"\n	<Amount>7720000</Amount>"
		+"\n	<Network>STEP2</Network>"
		+"\n	<ValidationStatus>V</ValidationStatus>"
		+"\n	<PaymentBeneficiary>NL39RABO0300065264</PaymentBeneficiary>"
		+"\n	<BatchFileID>5751</BatchFileID>"
		+"\n	<PaymentPriority>9999</PaymentPriority>"
		+"\n	<BatchMsgID>SOGENL2AXXX-20161201-5751-1</BatchMsgID>"
		+"\n	<LocalInstrumentType>CORE</LocalInstrumentType>"
		+"\n	<Document xmlns=\"urn:iso:std:iso:20022:tech:xsd:pacs.003.001.01MPM\">"
		+"\n		<pacs.003.001.01>"
		+"\n			<GrpHdr>"
		+"\n				<MsgId>SOGENL2AXXX-20161201-5751-1</MsgId>"
		+"\n				<CreDtTm>{0}T14:10:38.330+05:30</CreDtTm>"
		+"\n				<BtchBookg>true</BtchBookg>"
		+"\n				<NbOfTxs>{8}</NbOfTxs>"
		+"\n				<CtrlSum>{1}</CtrlSum>"
		+"\n				<TtlIntrBkSttlmAmt Ccy=\"EUR\">{2}</TtlIntrBkSttlmAmt>"
		+"\n				<IntrBkSttlmDt>{0}</IntrBkSttlmDt>"
		+"\n				<SttlmInf xmlns=\"urn:iso:std:iso:20022:tech:xsd:pacs.003.001.01MPM\">"
		+"\n					<SttlmMtd>CLRG</SttlmMtd>"
		+"\n					<ClrSys>"
		+"\n						<Prtry>ST2</Prtry>"
		+"\n					</ClrSys>"
		+"\n				</SttlmInf>"
		+"\n				<InstgAgt xmlns=\"urn:iso:std:iso:20022:tech:xsd:pacs.003.001.01MPM\">"
		+"\n					<FinInstnId>"
		+"\n						<BIC>SOGENL2AXXX</BIC>"
		+"\n					</FinInstnId>"
		+"\n				</InstgAgt>"
		+"\n			</GrpHdr>";
		  
	  
	  public static final String OutDDSettlementBody = 
		 "\n			<DrctDbtTxInf xmlns=\"urn:iso:std:iso:20022:tech:xsd:pacs.003.001.01MPM\">"
		+"\n				<PmtId>"
		+"\n					<InstrId>{3}</InstrId>"
		+"\n					<EndToEndId>{4}</EndToEndId>"
		+"\n					<TxId>SOGENL2AXXX-20161201-5751-35304</TxId>"
		+"\n				</PmtId>"
		+"\n				<PmtTpInf>"
		+"\n					<InstrPrty>HIGH</InstrPrty>"
		+"\n					<SvcLvl>"
		+"\n						<Cd>SEPA</Cd>"
		+"\n					</SvcLvl>"
		+"\n					<LclInstrm>"
		+"\n						<Cd>CORE</Cd>"
		+"\n					</LclInstrm>"
		+"\n					<SeqTp>FRST</SeqTp>"
		+"\n					<CtgyPurp>CORT</CtgyPurp>"
		+"\n				</PmtTpInf>"
		+"\n				<IntrBkSttlmAmt Ccy=\"EUR\">{1}</IntrBkSttlmAmt>"
		+"\n				<IntrBkSttlmDt>{0}</IntrBkSttlmDt>"
		+"\n				<InstdAmt Ccy=\"EUR\">{1}</InstdAmt>"
		+"\n				<XchgRate>1.00</XchgRate>"
		+"\n				<ChrgBr>SLEV</ChrgBr>"
		+"\n				<ReqdColltnDt>{0}</ReqdColltnDt>"
		+"\n				<DrctDbtTx>"
		+"\n					<MndtRltdInf>"
		+"\n						<MndtId>123456789</MndtId>"
		+"\n						<DtOfSgntr>{0}</DtOfSgntr>"
		+"\n					</MndtRltdInf>"
		+"\n					<CdtrSchmeId>"
		+"\n						<Id>"
		+"\n							<PrvtId>"
		+"\n								<Othr>"
		+"\n									<Id>{5}</Id>"
		+"\n									<SchmeNm>"
		+"\n										<Prtry>SEPA</Prtry>"
		+"\n									</SchmeNm>"
		+"\n								</Othr>"
		+"\n							</PrvtId>"
		+"\n						</Id>"
		+"\n					</CdtrSchmeId>"
		+"\n					<PreNtfctnId>p:PreNtfctnId</PreNtfctnId>"
		+"\n					<PreNtfctnDt>2016-06-24</PreNtfctnDt>"
		+"\n				</DrctDbtTx>"
		+"\n				<Cdtr>"
		+"\n					<Nm>Airtel User One</Nm>"
		+"\n					<PstlAdr>"
		+"\n						<Ctry>NL</Ctry>"
		+"\n					</PstlAdr>"
		+"\n					<CtryOfRes>NL</CtryOfRes>"
		+"\n				</Cdtr>"
		+"\n				<CdtrAcct>"
		+"\n					<Id>"
		+"\n						<IBAN>{6}</IBAN>"
		+"\n					</Id>"
		+"\n				</CdtrAcct>"
		+"\n				<CdtrAgt>"
		+"\n					<FinInstnId>"
		+"\n						<BIC>SOGENL2AXXX</BIC>"
		+"\n					</FinInstnId>"
		+"\n				</CdtrAgt>"
		+"\n				<Dbtr>"
		+"\n					<Nm>p:Nm</Nm>"
		+"\n					<PstlAdr>"
		+"\n						<Ctry>NL</Ctry>"
		+"\n					</PstlAdr>"
		+"\n					<Id>"
		+"\n						<PrvtId>"
		+"\n							<CstmrNb>1</CstmrNb>"
		+"\n							<Issr>Test</Issr>"
		+"\n						</PrvtId>"
		+"\n					</Id>"
		+"\n						<CtryOfRes>NL</CtryOfRes>"
		+"\n				</Dbtr>"
		+"\n					<DbtrAcct>"
		+"\n						<Id>"
		+"\n							<IBAN>{7}</IBAN>"
		+"\n						</Id>"
		+"\n					</DbtrAcct>"
		+"\n				<DbtrAgt>"
		+"\n					<FinInstnId>"
		+"\n						<BIC>STALNL2GXXX</BIC>"
		+"\n					</FinInstnId>"
		+"\n				</DbtrAgt>"
		+"\n				<Purp>"
		+"\n					<Cd>p:Cd</Cd>"
		+"\n				</Purp>"
		+"\n				<RmtInf>"
		+"\n					<Ustrd>Airtel Bill payment autodebit</Ustrd>"
		+"\n				</RmtInf>"
		+"\n				<UsrDfndFlds>"
		+"\n					<UsrDfndFld>"
		+"\n						<name>PseudoMessageType</name>"
		+"\n						<value>SettlementConfirmed</value>"
		+"\n					</UsrDfndFld>"
		+"\n				</UsrDfndFlds>"
		+"\n				<MPMEvnt>"
		+"\n					<name>DIRECT_DEBIT_TRANSMITTED</name>"
		+"\n					<description>Direct Debit is transmitted.</description>"
		+"\n					<source>SYSTEM</source>"
		+"\n				</MPMEvnt>"
		+"\n			</DrctDbtTxInf>";
	  
	  public static final String OutDDSettlementFooter = 
		 "\n		</pacs.003.001.01>"
		+"\n	</Document>"
		+"\n</MeridianMessage>";
	  
	  
	  public static final String InDDSettlementHeader = 
			  			 "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
			  			+"\n<MeridianMessage MessageType=\"ISO20022_MPM"+"\nDebit\" MessageFormat=\"StandardXML\" System=\"ISO20022\">"
					  	+"\n<CustomerID>1</CustomerID>"
					  	+"\n<MeridianMessageType>ISO20022_MPM"+"\nDebit</MeridianMessageType>"
					  	+"\n<ExternalMessageType>MPM"+"\nDebit</ExternalMessageType>"
					  	+"\n<InternalMessageType>P</InternalMessageType>"
					  	+"\n<HostID>MPM</HostID>"
					  	+"\n<TRNO>InDDtxn-{11}-0</TRNO>"
					  	+"\n<Direction>I</Direction>"
					  	+"\n<ValueDate>2016-12-5</ValueDate>"
					  	+"\n<CurrencyCode>EUR</CurrencyCode>"
					  	+"\n<Amount>2000</Amount>"
					  	+"\n<Network>STEP2</Network>"
					  	+"\n<SenderAddress>STALNL2GXXX</SenderAddress>"
					  	+"\n<DestinationAddress>SOGENL2AXXX</DestinationAddress>"
					  	+"\n<ValidationStatus>V</ValidationStatus>"
					  	+"\n<PaymentBeneficiary>NL39RABO0300065264</PaymentBeneficiary>"
					  	+"\n<BatchFileID>2414</BatchFileID>"
					  	+"\n<PaymentPriority>9999</PaymentPriority>"
					  	+"\n<TransactionID>InDDtxn-{11}-1</TransactionID>"
					  	+"\n<BatchMsgID>InDDGrp-{11}-1</BatchMsgID>"
					  	+"\n<LocalInstrumentType>CORE</LocalInstrumentType>"
					  	+"\n<Document xmlns=\"urn:iso:std:iso:20022:tech:xsd:pacs.003.001.01MPM\">"
					  	+"\n	<pacs.003.001.01>"
					  	+"\n		<GrpHdr>"
					  	+"\n			<MsgId>InDDGrpId-{11}--1</MsgId>"
					  	+"\n			<CreDtTm>{0}T15:03:01.352+05:30</CreDtTm>"
					  	+"\n			<BtchBookg>true</BtchBookg>"
					  	+"\n			<NbOfTxs>1</NbOfTxs>"
					  	+"\n			<TtlIntrBkSttlmAmt Ccy=\"EUR\">2.0</TtlIntrBkSttlmAmt>"
					  	+"\n			<IntrBkSttlmDt>{0}</IntrBkSttlmDt>"
					  	+"\n			<SttlmInf xmlns=\"urn:iso:std:iso:20022:tech:xsd:pacs.003.001.01MPM\">"
					  	+"\n			<SttlmMtd>CLRG</SttlmMtd>"
					  	+"\n				<ClrSys>"
					  	+"\n					<Prtry>STEP2</Prtry>"
					  	+"\n				</ClrSys>"
					  	+"\n				</SttlmInf>"
					  	+"\n				<InstdAgt xmlns=\"urn:iso:std:iso:20022:tech:xsd:pacs.003.001.01MPM\">"
					  	+"\n					<FinInstnId>"
					  	+"\n						<BIC>SOGENL2A</BIC>"
					  	+"\n					</FinInstnId>"
					  	+"\n				</InstdAgt>"
					  	+"\n		</GrpHdr>" ;
					  				
	  public static final String InDDSettlementBody = 
					  			
					  	 "\n		<DrctDbtTxInf xmlns=\"urn:iso:std:iso:20022:tech:xsd:pacs.003.001.01MPM\">"
					  	+"\n			<PmtId>"
						+"\n				<EndToEndId>End-{11}-{12}</EndToEndId>"
					  	+"\n				<TxId>Txn-{11}-{12}</TxId>"
					  	+"\n			</PmtId>"
					  	+"\n			<PmtTpInf>"
					  	+"\n				<SvcLvl>"
					  	+"\n					<Cd>SEPA</Cd>"
					  	+"\n				</SvcLvl>"
					  	+"\n				<LclInstrm>"
					  	+"\n					<Cd>CORE</Cd>"
						+"\n				</LclInstrm>"
						+"\n				<SeqTp>OOFF</SeqTp>"
						+"\n				<CdOrPrtry>"
						+"\n					<Cd>CORT</Cd>"
					  	+"\n				</CdOrPrtry>"
					  	+"\n			</PmtTpInf>"
					  	+"\n			<IntrBkSttlmAmt Ccy=\"EUR\">{1}</IntrBkSttlmAmt>"
					  	+"\n			<ChrgBr>SLEV</ChrgBr>"
					  	+"\n			<ReqdColltnDt>{0}</ReqdColltnDt>"
					  	+"\n			<DrctDbtTx>"
					  	+"\n				<MndtRltdInf>"
					  	+"\n					<MndtId>MndtId-{11}-{12}</MndtId>"
					  	+"\n					<DtOfSgntr>{0}</DtOfSgntr>"
					  	+"\n					<AmdmntInd>false</AmdmntInd>"
					  	+"\n				</MndtRltdInf>"
					  	+"\n				<CdtrSchmeId>"
					  	+"\n					<Id>"
					  	+"\n						<PrvtId>"
						+"\n							<Othr>"
					  	+"\n								<Id>SE97ZZZ1234567891</Id>"
  						+"\n								<SchmeNm>"
						+"\n									<Prtry>SEPA</Prtry>"
  						+"\n								</SchmeNm>"
						+"\n							</Othr>"
					  	+"\n						</PrvtId>"
					  	+"\n					</Id>"
					  	+"\n				</CdtrSchmeId>"
					  	+"\n			</DrctDbtTx>"
					  	+"\n			<Cdtr>"
					  	+"\n				<Nm>CreditorName</Nm>"
					  	+"\n				<PstlAdr>"
					  	+"\n					<AdrLine>Creditor Postal Address Line 1</AdrLine>"
					  	+"\n					<AdrLine>Creditor Postal Address Line 2</AdrLine>"
					  	+"\n					<Ctry>GB</Ctry>"
					  	+"\n				</PstlAdr>"
					  	+"\n			</Cdtr>"
					  	+"\n			<CdtrAcct>"
					  	+"\n				<Id>"
					  	+"\n					<IBAN>{6}</IBAN>"
					  	+"\n				</Id>"
					  	+"\n			</CdtrAcct>"
					  	+"\n			<CdtrAgt>"
					  	+"\n				<FinInstnId>"
					  	+"\n					<BIC>STALNL2GXXX</BIC>"
					  	+"\n				</FinInstnId>"
					  	+"\n			</CdtrAgt>"
					  	+"\n			<Dbtr>"
					  	+"\n				<Nm>DebtorName</Nm>"
					  	+"\n				<PstlAdr>"
					  	+"\n					<AdrLine>Debtor Postal Address Line 1</AdrLine>"
					  	+"\n					<AdrLine>Debtor Postal Address Line 2</AdrLine>"
					  	+"\n					<Ctry>GB</Ctry>"
					  	+"\n				</PstlAdr>"
					  	+"\n			</Dbtr>"
					  	+"\n			<DbtrAcct>"
					  	+"\n				<Id>"
					  	+"\n					<IBAN>{7}</IBAN>"
					  	+"\n				</Id>"
					  	+"\n			</DbtrAcct>"
					  	+"\n			<DbtrAgt>"
					  	+"\n				<FinInstnId>"
					  	+"\n					<BIC>SOGENL2AXXX</BIC>"
					  	+"\n				</FinInstnId>"
					  	+"\n			</DbtrAgt>"
					  	+"\n			<Purp>"
					  	+"\n				<Prtry>Purpose Choice Proprietary</Prtry>"
					  	+"\n			</Purp>"
					  	+"\n			<RmtInf>"
					  	+"\n				<Ustrd>RmtInf Unstructured</Ustrd>"
					  	+"\n			</RmtInf>"
					  	+"\n			<UsrDfndFlds>"
					  	+"\n				<UsrDfndFld>"
					  	+"\n					<name>PseudoMessageType</name>"
					  	+"\n					<value>SettlementConfirmed</value>"
					  	+"\n				</UsrDfndFld>"
					  	+"\n			</UsrDfndFlds>"
					  	+"\n			<MPMEvnt>"
					  	+"\n				<name>DIRECT_DEBIT_RECEIVED</name>"
					  	+"\n				<description>Direct Debit is received.</description>"
					  	+"\n				<source>SYSTEM</source>"
					  	+"\n			</MPMEvnt>"
						+"\n		</DrctDbtTxInf>";
	  
	  public static final String InDDSettlementFooter = 
					  	 "\n	</pacs.003.001.01>"
					  	+"\n	</Document>"
						+"\n</MeridianMessage>";

	  
	  
}
