public class DebitTrxTemplate {





public static final String header = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"+
"<p:Document xmlns:p=\"urn:iso:std:iso:20022:tech:xsd:pain.008.001.05\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xsi:schemaLocation=\"urn:iso:std:iso:20022:tech:xsd:pain.008.001.05 pain.008.001.05.ISO.STP2.xsd \">\n"+
"\n  <p:CstmrDrctDbtInitn>\n"+
"\n    <p:GrpHdr>\n"+
"\n      <p:MsgId>DirectDebit-Header-{0}--{1}</p:MsgId>\n"+
"\n      <p:CreDtTm>{7}T12:00:00</p:CreDtTm>\n"+
"\n      <p:Authstn>\n"+
"\n        <p:Cd>AUTH</p:Cd>\n"+
"\n      </p:Authstn>\n"+
"\n      <p:NbOfTxs>{8}</p:NbOfTxs>\n"+
"\n      <p:CtrlSum>{9}</p:CtrlSum>\n"+
"\n      <p:InitgPty>\n"+
"\n        <p:Nm>Airtel</p:Nm>\n"+
"\n        <p:PstlAdr>\n"+
"\n          <p:AdrTp>ADDR</p:AdrTp>\n"+
"\n          <p:Dept>Collections</p:Dept>\n"+
"\n          <p:SubDept>p:SubDept</p:SubDept>\n"+
"\n          <p:BldgNb>1</p:BldgNb>\n"+
"\n          <p:PstCd>560061</p:PstCd>\n"+
"\n          <p:TwnNm>Bengaluru</p:TwnNm>\n"+
"\n          <p:CtrySubDvsn>KA</p:CtrySubDvsn>\n"+
"\n          <p:Ctry>NL</p:Ctry>\n"+
"\n          <p:AdrLine>p:AdrLine</p:AdrLine>\n"+
"\n        </p:PstlAdr>\n"+
"\n        <p:Id>\n"+
"\n          <p:PrvtId>\n"+
"\n            <p:Othr>\n"+
"\n              <p:Id>{10}</p:Id>\n"+
"\n              <p:SchmeNm>\n"+
"\n                <p:Cd>p:Cd</p:Cd>\n"+
"\n              </p:SchmeNm>\n"+
"\n              <p:Issr>p:Issr</p:Issr>\n"+
"\n            </p:Othr>\n"+
"\n          </p:PrvtId>\n"+
"\n        </p:Id>\n"+
"\n        <p:CtryOfRes>NL</p:CtryOfRes>\n"+
"\n        <p:CtctDtls>\n"+
"\n          <p:NmPrfx>MIST</p:NmPrfx>\n"+
"\n          <p:Nm>Sunil Bharthi</p:Nm>\n"+
"\n          <p:PhneNb>+91-111111111111</p:PhneNb>\n"+
"\n          <p:MobNb>+91-111111111111</p:MobNb>\n"+
"\n          <p:FaxNb>+91-111111111111</p:FaxNb>\n"+
"\n          <p:EmailAdr>a@b.com</p:EmailAdr>\n"+
"\n          <p:Othr>p:Othr</p:Othr>\n"+
"\n        </p:CtctDtls>\n"+
"\n      </p:InitgPty>\n"+
"\n      <p:FwdgAgt>\n"+
"\n        <p:FinInstnId>\n"+
"\n          <p:BICFI>AAAAAAZ9</p:BICFI>\n"+
"\n          <p:ClrSysMmbId>\n"+
"\n            <p:ClrSysId>\n"+
"\n              <p:Cd>p:Cd</p:Cd>\n"+
"\n            </p:ClrSysId>\n"+
"\n            <p:MmbId>IN12ZZZ12345678</p:MmbId>\n"+
"\n          </p:ClrSysMmbId>\n"+
"\n          <p:Nm>p:Nm</p:Nm>\n"+
"\n          <p:PstlAdr>\n"+
"\n            <p:AdrTp>ADDR</p:AdrTp>\n"+
"\n            <p:Dept>p:Dept</p:Dept>\n"+
"\n            <p:SubDept>p:SubDept</p:SubDept>\n"+
"\n            <p:StrtNm>Kingdom St</p:StrtNm>\n"+
"\n            <p:BldgNb>1</p:BldgNb>\n"+
"\n            <p:PstCd>560061</p:PstCd>\n"+
"\n            <p:TwnNm>Bengaluru</p:TwnNm>\n"+
"\n            <p:CtrySubDvsn>KA</p:CtrySubDvsn>\n"+
"\n            <p:Ctry>NL</p:Ctry>\n"+
"\n            <p:AdrLine>p:AdrLine</p:AdrLine>\n"+
"\n          </p:PstlAdr>\n"+
"\n          <p:Othr>\n"+
"\n            <p:Id>p:Id</p:Id>\n"+
"\n            <p:SchmeNm>\n"+
"\n              <p:Cd>p:Cd</p:Cd>\n"+
"\n            </p:SchmeNm>\n"+
"\n            <p:Issr>p:Issr</p:Issr>\n"+
"\n          </p:Othr>\n"+
"\n        </p:FinInstnId>\n"+
"\n        <p:BrnchId>\n"+
"\n          <p:Id>88888888</p:Id>\n"+
"\n          <p:Nm>SomeBank</p:Nm>\n"+
"\n          <p:PstlAdr>\n"+
"\n            <p:AdrTp>ADDR</p:AdrTp>\n"+
"\n            <p:Dept>p:Dept</p:Dept>\n"+
"\n            <p:SubDept>p:SubDept</p:SubDept>\n"+
"\n            <p:StrtNm>Kingdom St</p:StrtNm>\n"+
"\n            <p:BldgNb>1</p:BldgNb>\n"+
"\n            <p:PstCd>560061</p:PstCd>\n"+
"\n            <p:TwnNm>Bengaluru</p:TwnNm>\n"+
"\n            <p:CtrySubDvsn>KA</p:CtrySubDvsn>\n"+
"\n            <p:Ctry>NL</p:Ctry>\n"+
"\n            <p:AdrLine>p:AdrLine</p:AdrLine>\n"+
"\n          </p:PstlAdr>\n"+
"\n        </p:BrnchId>\n"+
"\n      </p:FwdgAgt>\n"+
"\n    </p:GrpHdr>\n";






public static final String pmtInfo_header = 
"\n    <p:PmtInf>\n"+
"\n      <p:PmtInfId>DD-PytInfId-{0}-{1}</p:PmtInfId>\n"+
"\n      <p:PmtMtd>DD</p:PmtMtd>\n"+
"\n      <p:BtchBookg>false</p:BtchBookg>\n"+
"\n      <p:NbOfTxs>{8}</p:NbOfTxs>\n"+
"\n      <p:CtrlSum>{9}</p:CtrlSum>\n"+
"\n      <p:PmtTpInf>\n"+
"\n          <p:InstrPrty>HIGH</p:InstrPrty>\n"+
"\n          <p:SvcLvl>\n"+
"\n            <p:Cd>SEPA</p:Cd>\n"+
"\n          </p:SvcLvl>\n"+
"\n          <p:LclInstrm>\n"+
"\n            <p:Cd>{12}</p:Cd>\n"+
"\n          </p:LclInstrm>\n"+
"\n          <p:SeqTp>FRST</p:SeqTp>\n"+
"\n          <p:CtgyPurp>\n"+
"\n            <p:Cd>CORT</p:Cd>\n"+
"\n          </p:CtgyPurp>\n"+
"\n       </p:PmtTpInf>\n"+
"\n      <p:ReqdColltnDt>{7}</p:ReqdColltnDt>\n"+
"\n      <p:Cdtr>\n"+
"\n        <p:Nm>Airtel User One</p:Nm>\n"+
"\n        <p:PstlAdr>\n"+
"\n          <p:AdrTp>ADDR</p:AdrTp>\n"+
"\n          <p:Dept>p:Dept</p:Dept>\n"+
"\n          <p:SubDept>p:SubDept</p:SubDept>\n"+
"\n          <p:StrtNm>Kingdom St</p:StrtNm>\n"+
"\n          <p:BldgNb>1</p:BldgNb>\n"+
"\n          <p:PstCd>560061</p:PstCd>\n"+
"\n          <p:TwnNm>Bengaluru</p:TwnNm>\n"+
"\n          <p:CtrySubDvsn>KA</p:CtrySubDvsn>\n"+
"\n          <p:Ctry>NL</p:Ctry>\n"+
"\n          <p:AdrLine>p:AdrLine</p:AdrLine>\n"+
"\n        </p:PstlAdr>\n"+
"\n        <p:Id>\n"+
"\n          <p:OrgId>\n"+
"\n            <p:AnyBIC>AAAAAAZ9</p:AnyBIC>\n"+
"\n            <p:Othr>\n"+
"\n              <p:Id>11111</p:Id>\n"+
"\n              <p:SchmeNm>\n"+
"\n                <p:Cd>p:Cd</p:Cd>\n"+
"\n              </p:SchmeNm>\n"+
"\n              <p:Issr>p:Issr</p:Issr>\n"+
"\n            </p:Othr>\n"+
"\n          </p:OrgId>\n"+
"\n        </p:Id>\n"+
"\n        <p:CtryOfRes>NL</p:CtryOfRes>\n"+
"\n        <p:CtctDtls>\n"+
"\n          <p:NmPrfx>MIST</p:NmPrfx>\n"+
"\n          <p:Nm>Airtel User One</p:Nm>\n"+
"\n          <p:PhneNb>+91-111111111111</p:PhneNb>\n"+
"\n          <p:MobNb>+91-111111111111</p:MobNb>\n"+
"\n          <p:FaxNb>+91-111111111111</p:FaxNb>\n"+
"\n          <p:EmailAdr>a@b.com</p:EmailAdr>\n"+
"\n          <p:Othr>p:Othr</p:Othr>\n"+
"\n        </p:CtctDtls>\n"+
"\n      </p:Cdtr>\n"+
"\n      <p:CdtrAcct>\n"+
"\n        <p:Id>\n"+
"\n          <p:IBAN>{3}</p:IBAN>\n"+
"\n        </p:Id>\n"+
"\n        <p:Tp>\n"+
"\n          <p:Cd>p:Cd</p:Cd>\n"+
"\n        </p:Tp>\n"+
"\n        <p:Ccy>EUR</p:Ccy>\n"+
"\n        <p:Nm>Airtel</p:Nm>\n"+
"\n      </p:CdtrAcct>\n"+
"\n      <p:CdtrAgt>\n"+
"\n        <p:FinInstnId>\n"+
"\n          <p:BICFI>{4}</p:BICFI>\n"+
"\n          <p:ClrSysMmbId>\n"+
"\n            <p:ClrSysId>\n"+
"\n              <p:Cd>p:Cd</p:Cd>\n"+
"\n            </p:ClrSysId>\n"+
"\n            <p:MmbId>p:MmbId</p:MmbId>\n"+
"\n          </p:ClrSysMmbId>\n"+
"\n          <p:Nm>p:Nm</p:Nm>\n"+
"\n          <p:PstlAdr>\n"+
"\n            <p:AdrTp>ADDR</p:AdrTp>\n"+
"\n            <p:Dept>p:Dept</p:Dept>\n"+
"\n            <p:SubDept>p:SubDept</p:SubDept>\n"+
"\n            <p:StrtNm>Kingdom St</p:StrtNm>\n"+
"\n            <p:BldgNb>1</p:BldgNb>\n"+
"\n            <p:PstCd>560061</p:PstCd>\n"+
"\n            <p:TwnNm>Bengaluru</p:TwnNm>\n"+
"\n            <p:CtrySubDvsn>KA</p:CtrySubDvsn>\n"+
"\n            <p:Ctry>NL</p:Ctry>\n"+
"\n            <p:AdrLine>p:AdrLine</p:AdrLine>\n"+
"\n          </p:PstlAdr>\n"+
"\n          <p:Othr>\n"+
"\n            <p:Id>p:Id</p:Id>\n"+
"\n            <p:SchmeNm>\n"+
"\n              <p:Cd>p:Cd</p:Cd>\n"+
"\n            </p:SchmeNm>\n"+
"\n            <p:Issr>p:Issr</p:Issr>\n"+
"\n          </p:Othr>\n"+
"\n        </p:FinInstnId>\n"+
"\n        <p:BrnchId>\n"+
"\n          <p:Id>p:Id</p:Id>\n"+
"\n          <p:Nm>p:Nm</p:Nm>\n"+
"\n          <p:PstlAdr>\n"+
"\n            <p:AdrTp>ADDR</p:AdrTp>\n"+
"\n            <p:Dept>p:Dept</p:Dept>\n"+
"\n            <p:SubDept>p:SubDept</p:SubDept>\n"+
"\n            <p:StrtNm>Kingdom St</p:StrtNm>\n"+
"\n            <p:BldgNb>1</p:BldgNb>\n"+
"\n            <p:PstCd>560061</p:PstCd>\n"+
"\n            <p:TwnNm>Bengaluru</p:TwnNm>\n"+
"\n            <p:CtrySubDvsn>KA</p:CtrySubDvsn>\n"+
"\n            <p:Ctry>NL</p:Ctry>\n"+
"\n            <p:AdrLine>p:AdrLine</p:AdrLine>\n"+
"\n          </p:PstlAdr>\n"+
"\n        </p:BrnchId>\n"+
"\n      </p:CdtrAgt>\n"+
"\n      <p:CdtrAgtAcct>\n"+
"\n        <p:Id>\n"+
"\n          <p:IBAN>{3}</p:IBAN>\n"+
"\n        </p:Id>\n"+
"\n        <p:Tp>\n"+
"\n          <p:Cd>p:Cd</p:Cd>\n"+
"\n        </p:Tp>\n"+
"\n        <p:Ccy>EUR</p:Ccy>\n"+
"\n        <p:Nm>p:Nm</p:Nm>\n"+
"\n      </p:CdtrAgtAcct>\n"+
"\n      <p:ChrgBr>SLEV</p:ChrgBr>\n"+
"\n      <p:ChrgsAcct>\n"+
"\n        <p:Id>\n"+
"\n          <p:IBAN>{3}</p:IBAN>\n"+
"\n        </p:Id>\n"+
"\n        <p:Tp>\n"+
"\n          <p:Cd>p:Cd</p:Cd>\n"+
"\n        </p:Tp>\n"+
"\n        <p:Ccy>EUR</p:Ccy>\n"+
"\n        <p:Nm>p:Nm</p:Nm>\n"+
"\n      </p:ChrgsAcct>\n"+
"\n      <p:ChrgsAcctAgt>\n"+
"\n        <p:FinInstnId>\n"+
"\n          <p:BICFI>CCCCUS27</p:BICFI>\n"+
"\n          <p:ClrSysMmbId>\n"+
"\n            <p:ClrSysId>\n"+
"\n              <p:Cd>p:Cd</p:Cd>\n"+
"\n            </p:ClrSysId>\n"+
"\n            <p:MmbId>p:MmbId</p:MmbId>\n"+
"\n          </p:ClrSysMmbId>\n"+
"\n          <p:Nm>p:Nm</p:Nm>\n"+
"\n          <p:PstlAdr>\n"+
"\n            <p:AdrTp>ADDR</p:AdrTp>\n"+
"\n            <p:Dept>p:Dept</p:Dept>\n"+
"\n            <p:SubDept>p:SubDept</p:SubDept>\n"+
"\n            <p:StrtNm>Kingdom St</p:StrtNm>\n"+
"\n            <p:BldgNb>1</p:BldgNb>\n"+
"\n            <p:PstCd>560061</p:PstCd>\n"+
"\n            <p:TwnNm>Bengaluru</p:TwnNm>\n"+
"\n            <p:CtrySubDvsn>KA</p:CtrySubDvsn>\n"+
"\n            <p:Ctry>NL</p:Ctry>\n"+
"\n            <p:AdrLine>p:AdrLine</p:AdrLine>\n"+
"\n          </p:PstlAdr>\n"+
"\n          <p:Othr>\n"+
"\n            <p:Id>p:Id</p:Id>\n"+
"\n            <p:SchmeNm>\n"+
"\n              <p:Cd>p:Cd</p:Cd>\n"+
"\n            </p:SchmeNm>\n"+
"\n            <p:Issr>p:Issr</p:Issr>\n"+
"\n          </p:Othr>\n"+
"\n        </p:FinInstnId>\n"+
"\n        <p:BrnchId>\n"+
"\n          <p:Id>p:Id</p:Id>\n"+
"\n          <p:Nm>p:Nm</p:Nm>\n"+
"\n          <p:PstlAdr>\n"+
"\n            <p:AdrTp>ADDR</p:AdrTp>\n"+
"\n            <p:Dept>p:Dept</p:Dept>\n"+
"\n            <p:SubDept>p:SubDept</p:SubDept>\n"+
"\n            <p:StrtNm>Kingdom St</p:StrtNm>\n"+
"\n            <p:BldgNb>1</p:BldgNb>\n"+
"\n            <p:PstCd>560061</p:PstCd>\n"+
"\n            <p:TwnNm>Bengaluru</p:TwnNm>\n"+
"\n            <p:CtrySubDvsn>KA</p:CtrySubDvsn>\n"+
"\n            <p:Ctry>NL</p:Ctry>\n"+
"\n            <p:AdrLine>p:AdrLine</p:AdrLine>\n"+
"\n          </p:PstlAdr>\n"+
"\n        </p:BrnchId>\n"+
"\n      </p:ChrgsAcctAgt>\n"+
"\n      <p:CdtrSchmeId>\n"+
"\n            <p:Nm>Airtel</p:Nm>\n"+
"\n            <p:PstlAdr>\n"+
"\n              <p:AdrTp>ADDR</p:AdrTp>\n"+
"\n              <p:Dept>p:Dept</p:Dept>\n"+
"\n              <p:SubDept>p:SubDept</p:SubDept>\n"+
"\n              <p:StrtNm>Kingdom St</p:StrtNm>\n"+
"\n              <p:BldgNb>1</p:BldgNb>\n"+
"\n              <p:PstCd>560061</p:PstCd>\n"+
"\n              <p:TwnNm>Bengaluru</p:TwnNm>\n"+
"\n              <p:CtrySubDvsn>KA</p:CtrySubDvsn>\n"+
"\n              <p:Ctry>NL</p:Ctry>\n"+
"\n              <p:AdrLine>p:AdrLine</p:AdrLine>\n"+
"\n            </p:PstlAdr>\n"+
"\n            <p:Id>\n"+
"\n               <p:PrvtId>\n"+
"\n                   <p:Othr>\n"+
"\n                       <p:Id>{11}</p:Id>\n"+
"\n                       <p:SchmeNm>\n"+
"\n                           <p:Prtry>Airtel</p:Prtry>\n"+
"\n                       </p:SchmeNm>\n"+
"\n                       <p:Issr>p:Issr</p:Issr>\n"+
"\n                   </p:Othr>\n"+
"\n               </p:PrvtId>\n"+
"\n              <!-- <p:OrgId>\n"+
"\n                <p:AnyBIC>AAAAAAZ9</p:AnyBIC>\n"+
"\n                <p:Othr>\n"+
"\n                  <p:Id>p:Id</p:Id>\n"+
"\n                  <p:SchmeNm>\n"+
"\n                    <p:Cd>p:Cd</p:Cd>\n"+
"\n                  </p:SchmeNm>\n"+
"\n                  <p:Issr>p:Issr</p:Issr>\n"+
"\n                </p:Othr>\n"+
"\n              </p:OrgId>\n"+
"\n             -->\n"+
"\n            </p:Id>\n"+
"\n            <p:CtryOfRes>NL</p:CtryOfRes>\n"+
"\n            <p:CtctDtls>\n"+
"\n              <p:NmPrfx>DOCT</p:NmPrfx>\n"+
"\n              <p:Nm>p:Nm</p:Nm>\n"+
"\n              <p:PhneNb>+91-111111111111</p:PhneNb>\n"+
"\n              <p:MobNb>+91-111111111111</p:MobNb>\n"+
"\n              <p:FaxNb>+91-111111111111</p:FaxNb>\n"+
"\n              <p:EmailAdr>a@b.com</p:EmailAdr>\n"+
"\n              <p:Othr>p:Othr</p:Othr>\n"+
"\n            </p:CtctDtls>\n"+
"\n          </p:CdtrSchmeId>\n";

public static final String template = "	<p:DrctDbtTxInf>\n"+
"\n        <p:PmtId>\n"+
"\n          <p:InstrId>p:InstrId</p:InstrId>\n"+
"\n          <p:EndToEndId>End-DirectDBT-trx-{0}-{18}-{1}</p:EndToEndId>\n"+
"\n        </p:PmtId>\n"+
"\n        <p:InstdAmt Ccy=\"EUR\">{2}</p:InstdAmt>\n"+
"\n        <p:ChrgBr>SLEV</p:ChrgBr>\n"+
"\n        <p:DrctDbtTx>\n"+
"\n          <p:MndtRltdInf>\n"+
"\n            <p:MndtId>123456789</p:MndtId>\n"+
"\n            <p:DtOfSgntr>2015-05-03</p:DtOfSgntr>\n"+
"\n            <p:AmdmntInd>true</p:AmdmntInd>\n"+
"\n            <p:AmdmntInfDtls>\n"+
"\n              <p:OrgnlMndtId>123456789</p:OrgnlMndtId>\n"+
"\n              <p:OrgnlCdtrSchmeId>\n"+
"\n                <p:Nm>p:Nm</p:Nm>\n"+
"\n                <p:PstlAdr>\n"+
"\n                  <p:AdrTp>ADDR</p:AdrTp>\n"+
"\n                  <p:Dept>p:Dept</p:Dept>\n"+
"\n                  <p:SubDept>p:SubDept</p:SubDept>\n"+
"\n                  <p:StrtNm>Kingdom St</p:StrtNm>\n"+
"\n                  <p:BldgNb>1</p:BldgNb>\n"+
"\n                  <p:PstCd>560061</p:PstCd>\n"+
"\n                  <p:TwnNm>Bengaluru</p:TwnNm>\n"+
"\n                  <p:CtrySubDvsn>KA</p:CtrySubDvsn>\n"+
"\n                  <p:Ctry>NL</p:Ctry>\n"+
"\n                  <p:AdrLine>p:AdrLine</p:AdrLine>\n"+
"\n                </p:PstlAdr>\n"+
"\n                <p:Id>\n"+
"\n                  <p:OrgId>\n"+
"\n                    <p:AnyBIC>AAAAAAZ9</p:AnyBIC>\n"+
"\n                    <p:Othr>\n"+
"\n                      <p:Id>p:Id</p:Id>\n"+
"\n                      <p:SchmeNm>\n"+
"\n                        <p:Cd>p:Cd</p:Cd>\n"+
"\n                      </p:SchmeNm>\n"+
"\n                      <p:Issr>p:Issr</p:Issr>\n"+
"\n                    </p:Othr>\n"+
"\n                  </p:OrgId>\n"+
"\n                </p:Id>\n"+
"\n                <p:CtryOfRes>NL</p:CtryOfRes>\n"+
"\n                <p:CtctDtls>\n"+
"\n                  <p:NmPrfx>DOCT</p:NmPrfx>\n"+
"\n                  <p:Nm>p:Nm</p:Nm>\n"+
"\n                  <p:PhneNb>+91-111111111111</p:PhneNb>\n"+
"\n                  <p:MobNb>+91-111111111111</p:MobNb>\n"+
"\n                  <p:FaxNb>+91-111111111111</p:FaxNb>\n"+
"\n                  <p:EmailAdr>a@b.com</p:EmailAdr>\n"+
"\n                  <p:Othr>p:Othr</p:Othr>\n"+
"\n                </p:CtctDtls>\n"+
"\n              </p:OrgnlCdtrSchmeId>\n"+
"\n              <p:OrgnlCdtrAgt>\n"+
"\n                <p:FinInstnId>\n"+
"\n                  <p:BICFI>CCCCUS27</p:BICFI>\n"+
"\n                  <p:ClrSysMmbId>\n"+
"\n                    <p:ClrSysId>\n"+
"\n                      <p:Cd>p:Cd</p:Cd>\n"+
"\n                    </p:ClrSysId>\n"+
"\n                    <p:MmbId>p:MmbId</p:MmbId>\n"+
"\n                  </p:ClrSysMmbId>\n"+
"\n                  <p:Nm>p:Nm</p:Nm>\n"+
"\n                  <p:PstlAdr>\n"+
"\n                    <p:AdrTp>ADDR</p:AdrTp>\n"+
"\n                    <p:Dept>p:Dept</p:Dept>\n"+
"\n                    <p:SubDept>p:SubDept</p:SubDept>\n"+
"\n                    <p:StrtNm>Kingdom St</p:StrtNm>\n"+
"\n                    <p:BldgNb>1</p:BldgNb>\n"+
"\n                    <p:PstCd>560061</p:PstCd>\n"+
"\n                    <p:TwnNm>Bengaluru</p:TwnNm>\n"+
"\n                    <p:CtrySubDvsn>KA</p:CtrySubDvsn>\n"+
"\n                    <p:Ctry>NL</p:Ctry>\n"+
"\n                    <p:AdrLine>p:AdrLine</p:AdrLine>\n"+
"\n                  </p:PstlAdr>\n"+
"\n                  <p:Othr>\n"+
"\n                    <p:Id>p:Id</p:Id>\n"+
"\n                    <p:SchmeNm>\n"+
"\n                      <p:Cd>p:Cd</p:Cd>\n"+
"\n                    </p:SchmeNm>\n"+
"\n                    <p:Issr>p:Issr</p:Issr>\n"+
"\n                  </p:Othr>\n"+
"\n                </p:FinInstnId>\n"+
"\n                <p:BrnchId>\n"+
"\n                  <p:Id>p:Id</p:Id>\n"+
"\n                  <p:Nm>p:Nm</p:Nm>\n"+
"\n                  <p:PstlAdr>\n"+
"\n                    <p:AdrTp>ADDR</p:AdrTp>\n"+
"\n                    <p:Dept>p:Dept</p:Dept>\n"+
"\n                    <p:SubDept>p:SubDept</p:SubDept>\n"+
"\n                    <p:StrtNm>Kingdom St</p:StrtNm>\n"+
"\n                    <p:BldgNb>1</p:BldgNb>\n"+
"\n                    <p:PstCd>560061</p:PstCd>\n"+
"\n                    <p:TwnNm>Bengaluru</p:TwnNm>\n"+
"\n                    <p:CtrySubDvsn>KA</p:CtrySubDvsn>\n"+
"\n                    <p:Ctry>NL</p:Ctry>\n"+
"\n                    <p:AdrLine>p:AdrLine</p:AdrLine>\n"+
"\n                  </p:PstlAdr>\n"+
"\n                </p:BrnchId>\n"+
"\n              </p:OrgnlCdtrAgt>\n"+
"\n              <p:OrgnlCdtrAgtAcct>\n"+
"\n                <p:Id>\n"+
"\n                  <p:IBAN>{3}</p:IBAN>\n"+
"\n                </p:Id>\n"+
"\n                <p:Tp>\n"+
"\n                  <p:Cd>p:Cd</p:Cd>\n"+
"\n                </p:Tp>\n"+
"\n                <p:Ccy>EUR</p:Ccy>\n"+
"\n                <p:Nm>p:Nm</p:Nm>\n"+
"\n              </p:OrgnlCdtrAgtAcct>\n"+
"\n              <p:OrgnlDbtr>\n"+
"\n                <p:Nm>p:Nm</p:Nm>\n"+
"\n                <p:PstlAdr>\n"+
"\n                  <p:AdrTp>ADDR</p:AdrTp>\n"+
"\n                  <p:Dept>p:Dept</p:Dept>\n"+
"\n                  <p:SubDept>p:SubDept</p:SubDept>\n"+
"\n                  <p:StrtNm>Kingdom St</p:StrtNm>\n"+
"\n                  <p:BldgNb>1</p:BldgNb>\n"+
"\n                  <p:PstCd>560061</p:PstCd>\n"+
"\n                  <p:TwnNm>Bengaluru</p:TwnNm>\n"+
"\n                  <p:CtrySubDvsn>KA</p:CtrySubDvsn>\n"+
"\n                  <p:Ctry>NL</p:Ctry>\n"+
"\n                  <p:AdrLine>p:AdrLine</p:AdrLine>\n"+
"\n                </p:PstlAdr>\n"+
"\n                <p:Id>\n"+
"\n                  <p:OrgId>\n"+
"\n                    <p:AnyBIC>AAAAAAZ9</p:AnyBIC>\n"+
"\n                    <p:Othr>\n"+
"\n                      <p:Id>p:Id</p:Id>\n"+
"\n                      <p:SchmeNm>\n"+
"\n                        <p:Cd>p:Cd</p:Cd>\n"+
"\n                      </p:SchmeNm>\n"+
"\n                      <p:Issr>p:Issr</p:Issr>\n"+
"\n                    </p:Othr>\n"+
"\n                  </p:OrgId>\n"+
"\n                </p:Id>\n"+
"\n                <p:CtryOfRes>NL</p:CtryOfRes>\n"+
"\n                <p:CtctDtls>\n"+
"\n                  <p:NmPrfx>DOCT</p:NmPrfx>\n"+
"\n                  <p:Nm>p:Nm</p:Nm>\n"+
"\n                  <p:PhneNb>+91-111111111111</p:PhneNb>\n"+
"\n                  <p:MobNb>+91-111111111111</p:MobNb>\n"+
"\n                  <p:FaxNb>+91-111111111111</p:FaxNb>\n"+
"\n                  <p:EmailAdr>a@b.com</p:EmailAdr>\n"+
"\n                  <p:Othr>p:Othr</p:Othr>\n"+
"\n                </p:CtctDtls>\n"+
"\n              </p:OrgnlDbtr>\n"+
"\n              <p:OrgnlDbtrAcct>\n"+
"\n                <p:Id>\n"+
"\n                  <p:IBAN>{5}</p:IBAN>\n"+
"\n                </p:Id>\n"+
"\n                <p:Tp>\n"+
"\n                  <p:Cd>p:Cd</p:Cd>\n"+
"\n                </p:Tp>\n"+
"\n                <p:Ccy>EUR</p:Ccy>\n"+
"\n                <p:Nm>p:Nm</p:Nm>\n"+
"\n              </p:OrgnlDbtrAcct>\n"+
"\n              <p:OrgnlDbtrAgt>\n"+
"\n                <p:FinInstnId>\n"+
"\n                  <p:BICFI>{6}</p:BICFI>\n"+
"\n                  <p:ClrSysMmbId>\n"+
"\n                    <p:ClrSysId>\n"+
"\n                      <p:Cd>p:Cd</p:Cd>\n"+
"\n                    </p:ClrSysId>\n"+
"\n                    <p:MmbId>p:MmbId</p:MmbId>\n"+
"\n                  </p:ClrSysMmbId>\n"+
"\n                  <p:Nm>p:Nm</p:Nm>\n"+
"\n                  <p:PstlAdr>\n"+
"\n                    <p:AdrTp>ADDR</p:AdrTp>\n"+
"\n                    <p:Dept>p:Dept</p:Dept>\n"+
"\n                    <p:SubDept>p:SubDept</p:SubDept>\n"+
"\n                    <p:StrtNm>Kingdom St</p:StrtNm>\n"+
"\n                    <p:BldgNb>1</p:BldgNb>\n"+
"\n                    <p:PstCd>560061</p:PstCd>\n"+
"\n                    <p:TwnNm>Bengaluru</p:TwnNm>\n"+
"\n                    <p:CtrySubDvsn>KA</p:CtrySubDvsn>\n"+
"\n                    <p:Ctry>NL</p:Ctry>\n"+
"\n                    <p:AdrLine>p:AdrLine</p:AdrLine>\n"+
"\n                  </p:PstlAdr>\n"+
"\n                  <p:Othr>\n"+
"\n                    <p:Id>p:Id</p:Id>\n"+
"\n                    <p:SchmeNm>\n"+
"\n                      <p:Cd>p:Cd</p:Cd>\n"+
"\n                    </p:SchmeNm>\n"+
"\n                    <p:Issr>p:Issr</p:Issr>\n"+
"\n                  </p:Othr>\n"+
"\n                </p:FinInstnId>\n"+
"\n                <p:BrnchId>\n"+
"\n                  <p:Id>p:Id</p:Id>\n"+
"\n                  <p:Nm>p:Nm</p:Nm>\n"+
"\n                  <p:PstlAdr>\n"+
"\n                    <p:AdrTp>ADDR</p:AdrTp>\n"+
"\n                    <p:Dept>p:Dept</p:Dept>\n"+
"\n                    <p:SubDept>p:SubDept</p:SubDept>\n"+
"\n                    <p:StrtNm>Kingdom St</p:StrtNm>\n"+
"\n                    <p:BldgNb>1</p:BldgNb>\n"+
"\n                    <p:PstCd>560061</p:PstCd>\n"+
"\n                    <p:TwnNm>Bengaluru</p:TwnNm>\n"+
"\n                    <p:CtrySubDvsn>KA</p:CtrySubDvsn>\n"+
"\n                    <p:Ctry>NL</p:Ctry>\n"+
"\n                    <p:AdrLine>p:AdrLine</p:AdrLine>\n"+
"\n                  </p:PstlAdr>\n"+
"\n                </p:BrnchId>\n"+
"\n              </p:OrgnlDbtrAgt>\n"+
"\n              <p:OrgnlDbtrAgtAcct>\n"+
"\n                <p:Id>\n"+
"\n                  <p:IBAN>{5}</p:IBAN>\n"+
"\n                </p:Id>\n"+
"\n                <p:Tp>\n"+
"\n                  <p:Cd>p:Cd</p:Cd>\n"+
"\n                </p:Tp>\n"+
"\n                <p:Ccy>EUR</p:Ccy>\n"+
"\n                <p:Nm>p:Nm</p:Nm>\n"+
"\n              </p:OrgnlDbtrAgtAcct>\n"+
"\n              <p:OrgnlFnlColltnDt>{7}</p:OrgnlFnlColltnDt>\n"+
"\n              <p:OrgnlFrqcy>\n"+
"\n                <p:Tp>YEAR</p:Tp>\n"+
"\n              </p:OrgnlFrqcy>\n"+
"\n              <p:OrgnlRsn>\n"+
"\n                <p:Cd>p:Cd</p:Cd>\n"+
"\n              </p:OrgnlRsn>\n"+
"\n            </p:AmdmntInfDtls>\n"+
"\n            <p:ElctrncSgntr>p:ElctrncSgntr</p:ElctrncSgntr>\n"+
"\n            <p:FrstColltnDt>2016-06-27</p:FrstColltnDt>\n"+
"\n            <p:FnlColltnDt>{7}</p:FnlColltnDt>\n"+
"\n            <p:Frqcy>\n"+
"\n              <p:Tp>YEAR</p:Tp>\n"+
"\n            </p:Frqcy>\n"+
"\n            <p:Rsn>\n"+
"\n              <p:Cd>p:Cd</p:Cd>\n"+
"\n            </p:Rsn>\n"+
"\n          </p:MndtRltdInf>\n"+
"\n          <p:PreNtfctnId>p:PreNtfctnId</p:PreNtfctnId>\n"+
"\n          <p:PreNtfctnDt>2016-06-24</p:PreNtfctnDt>\n"+
"\n        </p:DrctDbtTx>\n"+
"\n        <p:DbtrAgt>\n"+
"\n          <p:FinInstnId>\n"+
"\n            <p:BICFI>{6}</p:BICFI>    \n"+
"\n            <p:ClrSysMmbId>\n"+
"\n              <p:ClrSysId>\n"+
"\n                <p:Cd>p:Cd</p:Cd>\n"+
"\n              </p:ClrSysId>\n"+
"\n              <p:MmbId>p:MmbId</p:MmbId>\n"+
"\n            </p:ClrSysMmbId>\n"+
"\n            <p:Nm>p:Nm</p:Nm>\n"+
"\n            <p:PstlAdr>\n"+
"\n              <p:AdrTp>ADDR</p:AdrTp>\n"+
"\n              <p:Dept>p:Dept</p:Dept>\n"+
"\n              <p:SubDept>p:SubDept</p:SubDept>\n"+
"\n              <p:StrtNm>Kingdom Street</p:StrtNm>\n"+
"\n              <p:BldgNb>1</p:BldgNb>\n"+
"\n              <p:PstCd>560061</p:PstCd>\n"+
"\n              <p:TwnNm>Town</p:TwnNm>\n"+
"\n              <p:CtrySubDvsn>KA</p:CtrySubDvsn>\n"+
"\n              <p:Ctry>NL</p:Ctry>\n"+
"\n              <p:AdrLine>p:AdrLine</p:AdrLine>\n"+
"\n            </p:PstlAdr>\n"+
"\n            <p:Othr>\n"+
"\n              <p:Id>p:Id</p:Id>\n"+
"\n              <p:SchmeNm>\n"+
"\n                <p:Cd>p:Cd</p:Cd>\n"+
"\n              </p:SchmeNm>\n"+
"\n              <p:Issr>p:Issr</p:Issr>\n"+
"\n            </p:Othr>\n"+
"\n          </p:FinInstnId>\n"+
"\n          <p:BrnchId>\n"+
"\n            <p:Id>p:Id</p:Id>\n"+
"\n            <p:Nm>p:Nm</p:Nm>\n"+
"\n            <p:PstlAdr>\n"+
"\n              <p:AdrTp>ADDR</p:AdrTp>\n"+
"\n              <p:Dept>p:Dept</p:Dept>\n"+
"\n              <p:SubDept>p:SubDept</p:SubDept>\n"+
"\n              <p:StrtNm>Kingdom St</p:StrtNm>\n"+
"\n              <p:BldgNb>1</p:BldgNb>\n"+
"\n              <p:PstCd>560061</p:PstCd>\n"+
"\n              <p:TwnNm>Bengaluru</p:TwnNm>\n"+
"\n              <p:CtrySubDvsn>KA</p:CtrySubDvsn>\n"+
"\n              <p:Ctry>NL</p:Ctry>\n"+
"\n              <p:AdrLine>p:AdrLine</p:AdrLine>\n"+
"\n            </p:PstlAdr>\n"+
"\n          </p:BrnchId>\n"+
"\n        </p:DbtrAgt>\n"+
"\n        <p:DbtrAgtAcct>\n"+
"\n          <p:Id>\n"+
"\n            <p:IBAN>{5}</p:IBAN>\n"+
"\n          </p:Id>\n"+
"\n          <p:Tp>\n"+
"\n            <p:Cd>p:Cd</p:Cd>\n"+
"\n          </p:Tp>\n"+
"\n          <p:Ccy>EUR</p:Ccy>\n"+
"\n          <p:Nm>p:Nm</p:Nm>\n"+
"\n        </p:DbtrAgtAcct>\n"+
"\n        <p:Dbtr>\n"+
"\n          <p:Nm>p:Nm</p:Nm>\n"+
"\n          <p:PstlAdr>\n"+
"\n            <p:AdrTp>ADDR</p:AdrTp>\n"+
"\n            <p:Dept>p:Dept</p:Dept>\n"+
"\n            <p:SubDept>p:SubDept</p:SubDept>\n"+
"\n            <p:StrtNm>Kingdom St</p:StrtNm>\n"+
"\n            <p:BldgNb>1</p:BldgNb>\n"+
"\n            <p:PstCd>560061</p:PstCd>\n"+
"\n            <p:TwnNm>Bengaluru</p:TwnNm>\n"+
"\n            <p:CtrySubDvsn>KA</p:CtrySubDvsn>\n"+
"\n            <p:Ctry>NL</p:Ctry>\n"+
"\n            <p:AdrLine>p:AdrLine</p:AdrLine>\n"+
"\n          </p:PstlAdr>\n"+
"\n          <p:Id>\n"+
"\n            <p:OrgId>\n"+
"\n              <p:AnyBIC>AAAAAAZ9</p:AnyBIC>\n"+
"\n              <p:Othr>\n"+
"\n                <p:Id>p:Id</p:Id>\n"+
"\n                <p:SchmeNm>\n"+
"\n                  <p:Cd>p:Cd</p:Cd>\n"+
"\n                </p:SchmeNm>\n"+
"\n                <p:Issr>p:Issr</p:Issr>\n"+
"\n              </p:Othr>\n"+
"\n            </p:OrgId>\n"+
"\n          </p:Id>\n"+
"\n          <p:CtryOfRes>NL</p:CtryOfRes>\n"+
"\n          <p:CtctDtls>\n"+
"\n            <p:NmPrfx>DOCT</p:NmPrfx>\n"+
"\n            <p:Nm>p:Nm</p:Nm>\n"+
"\n            <p:PhneNb>+91-111111111111</p:PhneNb>\n"+
"\n            <p:MobNb>+91-111111111111</p:MobNb>\n"+
"\n            <p:FaxNb>+91-111111111111</p:FaxNb>\n"+
"\n            <p:EmailAdr>a@b.com</p:EmailAdr>\n"+
"\n            <p:Othr>p:Othr</p:Othr>\n"+
"\n          </p:CtctDtls>\n"+
"\n        </p:Dbtr>\n"+
"\n        <p:DbtrAcct>\n"+
"\n          <p:Id>\n"+
"\n            <p:IBAN>{5}</p:IBAN>\n"+
"\n          </p:Id>\n"+
"\n          <p:Tp>\n"+
"\n            <p:Cd>p:Cd</p:Cd>\n"+
"\n          </p:Tp>\n"+
"\n          <p:Ccy>EUR</p:Ccy>\n"+
"\n          <p:Nm>p:Nm</p:Nm>\n"+
"\n        </p:DbtrAcct>\n"+
"\n        <p:UltmtDbtr>\n"+
"\n          <p:Nm>p:Nm</p:Nm>\n"+
"\n          <p:PstlAdr>\n"+
"\n            <p:AdrTp>ADDR</p:AdrTp>\n"+
"\n            <p:Dept>p:Dept</p:Dept>\n"+
"\n            <p:SubDept>p:SubDept</p:SubDept>\n"+
"\n            <p:StrtNm>Kingdom St</p:StrtNm>\n"+
"\n            <p:BldgNb>1</p:BldgNb>\n"+
"\n            <p:PstCd>560061</p:PstCd>\n"+
"\n            <p:TwnNm>Bengaluru</p:TwnNm>\n"+
"\n            <p:CtrySubDvsn>KA</p:CtrySubDvsn>\n"+
"\n            <p:Ctry>NL</p:Ctry>\n"+
"\n            <p:AdrLine>p:AdrLine</p:AdrLine>\n"+
"\n          </p:PstlAdr>\n"+
"\n          <p:Id>\n"+
"\n            <p:OrgId>\n"+
"\n              <p:AnyBIC>AAAAAAZ9</p:AnyBIC>\n"+
"\n              <p:Othr>\n"+
"\n                <p:Id>p:Id</p:Id>\n"+
"\n                <p:SchmeNm>\n"+
"\n                  <p:Cd>p:Cd</p:Cd>\n"+
"\n                </p:SchmeNm>\n"+
"\n                <p:Issr>p:Issr</p:Issr>\n"+
"\n              </p:Othr>\n"+
"\n            </p:OrgId>\n"+
"\n          </p:Id>\n"+
"\n          <p:CtryOfRes>NL</p:CtryOfRes>\n"+
"\n          <p:CtctDtls>\n"+
"\n            <p:NmPrfx>DOCT</p:NmPrfx>\n"+
"\n            <p:Nm>p:Nm</p:Nm>\n"+
"\n            <p:PhneNb>+91-111111111111</p:PhneNb>\n"+
"\n            <p:MobNb>+91-111111111111</p:MobNb>\n"+
"\n            <p:FaxNb>+91-111111111111</p:FaxNb>\n"+
"\n            <p:EmailAdr>a@b.com</p:EmailAdr>\n"+
"\n            <p:Othr>p:Othr</p:Othr>\n"+
"\n          </p:CtctDtls>\n"+
"\n        </p:UltmtDbtr>\n"+
"\n        <p:InstrForCdtrAgt>p:InstrForCdtrAgt</p:InstrForCdtrAgt>\n"+
"\n        <p:Purp>\n"+
"\n          <p:Cd>p:Cd</p:Cd>\n"+
"\n        </p:Purp>\n"+
"\n        <p:RgltryRptg>\n"+
"\n          <p:DbtCdtRptgInd>CRED</p:DbtCdtRptgInd>\n"+
"\n          <p:Authrty>\n"+
"\n            <p:Nm>p:Nm</p:Nm>\n"+
"\n            <p:Ctry>NL</p:Ctry>\n"+
"\n          </p:Authrty>\n"+
"\n          <p:Dtls>\n"+
"\n            <p:Tp>p:Tp</p:Tp>\n"+
"\n            <p:Dt>2016-06-24</p:Dt>\n"+
"\n            <p:Ctry>NL</p:Ctry>\n"+
"\n            <p:Cd>p:Cd</p:Cd>\n"+
"\n            <p:Amt Ccy=\"EUR\">122.00</p:Amt>\n"+
"\n            <p:Inf>p:Inf</p:Inf>\n"+
"\n          </p:Dtls>\n"+
"\n        </p:RgltryRptg>\n"+
"\n        <p:Tax>\n"+
"\n          <p:Cdtr>\n"+
"\n            <p:TaxId>p:TaxId</p:TaxId>\n"+
"\n            <p:RegnId>p:RegnId</p:RegnId>\n"+
"\n            <p:TaxTp>p:TaxTp</p:TaxTp>\n"+
"\n          </p:Cdtr>\n"+
"\n          <p:Dbtr>\n"+
"\n            <p:TaxId>p:TaxId</p:TaxId>\n"+
"\n            <p:RegnId>p:RegnId</p:RegnId>\n"+
"\n            <p:TaxTp>p:TaxTp</p:TaxTp>\n"+
"\n            <p:Authstn>\n"+
"\n              <p:Titl>p:Titl</p:Titl>\n"+
"\n              <p:Nm>p:Nm</p:Nm>\n"+
"\n            </p:Authstn>\n"+
"\n          </p:Dbtr>\n"+
"\n          <p:AdmstnZn>p:AdmstnZn</p:AdmstnZn>\n"+
"\n          <p:RefNb>p:RefNb</p:RefNb>\n"+
"\n          <p:Mtd>p:Mtd</p:Mtd>\n"+
"\n          <p:TtlTaxblBaseAmt Ccy=\"EUR\">10.0</p:TtlTaxblBaseAmt>\n"+
"\n          <p:TtlTaxAmt Ccy=\"EUR\">10.0</p:TtlTaxAmt>\n"+
"\n          <p:Dt>2016-06-24</p:Dt>\n"+
"\n          <p:SeqNb>0.0</p:SeqNb>\n"+
"\n          <p:Rcrd>\n"+
"\n            <p:Tp>p:Tp</p:Tp>\n"+
"\n            <p:Ctgy>p:Ctgy</p:Ctgy>\n"+
"\n            <p:CtgyDtls>p:CtgyDtls</p:CtgyDtls>\n"+
"\n            <p:DbtrSts>p:DbtrSts</p:DbtrSts>\n"+
"\n            <p:CertId>p:CertId</p:CertId>\n"+
"\n            <p:FrmsCd>p:FrmsCd</p:FrmsCd>\n"+
"\n            <p:Prd>\n"+
"\n              <p:Yr>2016-06-24</p:Yr>\n"+
"\n              <p:Tp>MM01</p:Tp>\n"+
"\n              <p:FrToDt>\n"+
"\n                <p:FrDt>2016-06-24</p:FrDt>\n"+
"\n                <p:ToDt>2016-06-24</p:ToDt>\n"+
"\n              </p:FrToDt>\n"+
"\n            </p:Prd>\n"+
"\n            <p:TaxAmt>\n"+
"\n              <p:Rate>0.0</p:Rate>\n"+
"\n              <p:TaxblBaseAmt Ccy=\"EUR\">10.0</p:TaxblBaseAmt>\n"+
"\n              <p:TtlAmt Ccy=\"EUR\">10.0</p:TtlAmt>\n"+
"\n              <p:Dtls>\n"+
"\n                <p:Prd>\n"+
"\n                  <p:Yr>2016-06-24</p:Yr>\n"+
"\n                  <p:Tp>MM01</p:Tp>\n"+
"\n                  <p:FrToDt>\n"+
"\n                    <p:FrDt>2016-06-24</p:FrDt>\n"+
"\n                    <p:ToDt>2016-06-24</p:ToDt>\n"+
"\n                  </p:FrToDt>\n"+
"\n                </p:Prd>\n"+
"\n                <p:Amt Ccy=\"EUR\">10.0</p:Amt>\n"+
"\n              </p:Dtls>\n"+
"\n            </p:TaxAmt>\n"+
"\n            <p:AddtlInf>p:AddtlInf</p:AddtlInf>\n"+
"\n          </p:Rcrd>\n"+
"\n        </p:Tax>\n"+
"\n        <p:RltdRmtInf>\n"+
"\n          <p:RmtId>p:RmtId</p:RmtId>\n"+
"\n          <p:RmtLctnDtls>\n"+
"\n            <p:Mtd>FAXI</p:Mtd>\n"+
"\n            <p:ElctrncAdr>p:ElctrncAdr</p:ElctrncAdr>\n"+
"\n            <p:PstlAdr>\n"+
"\n              <p:Nm>p:Nm</p:Nm>\n"+
"\n              <p:Adr>\n"+
"\n                <p:AdrTp>ADDR</p:AdrTp>\n"+
"\n                <p:Dept>p:Dept</p:Dept>\n"+
"\n                <p:SubDept>p:SubDept</p:SubDept>\n"+
"\n                <p:StrtNm>Kingdom St</p:StrtNm>\n"+
"\n                <p:BldgNb>1</p:BldgNb>\n"+
"\n                <p:PstCd>560061</p:PstCd>\n"+
"\n                <p:TwnNm>Bengaluru</p:TwnNm>\n"+
"\n                <p:CtrySubDvsn>KA</p:CtrySubDvsn>\n"+
"\n                <p:Ctry>NL</p:Ctry>\n"+
"\n                <p:AdrLine>p:AdrLine</p:AdrLine>\n"+
"\n              </p:Adr>\n"+
"\n            </p:PstlAdr>\n"+
"\n          </p:RmtLctnDtls>\n"+
"\n        </p:RltdRmtInf>\n"+
"\n        <p:RmtInf>\n"+
"\n          <p:Ustrd>Airtel Bill payment autodebit</p:Ustrd>\n"+
"\n          <p:Strd>\n"+
"\n            <p:RfrdDocInf>\n"+
"\n              <p:Tp>\n"+
"\n                <p:CdOrPrtry>\n"+
"\n                  <p:Cd>MSIN</p:Cd>\n"+
"\n                </p:CdOrPrtry>\n"+
"\n                <p:Issr>p:Issr</p:Issr>\n"+
"\n              </p:Tp>\n"+
"\n              <p:Nb>p:Nb</p:Nb>\n"+
"\n              <p:RltdDt>2016-06-24</p:RltdDt>\n"+
"\n            </p:RfrdDocInf>\n"+
"\n            <p:RfrdDocAmt>\n"+
"\n              <p:DuePyblAmt Ccy=\"EUR\">122.00</p:DuePyblAmt>\n"+
"\n              <p:DscntApldAmt>\n"+
"\n                <p:Tp>\n"+
"\n                  <p:Cd>p:Cd</p:Cd>\n"+
"\n                </p:Tp>\n"+
"\n                <p:Amt Ccy=\"EUR\">122.00</p:Amt>\n"+
"\n              </p:DscntApldAmt>\n"+
"\n              <p:CdtNoteAmt Ccy=\"EUR\">10.0</p:CdtNoteAmt>\n"+
"\n              <p:TaxAmt>\n"+
"\n                <p:Tp>\n"+
"\n                  <p:Cd>p:Cd</p:Cd>\n"+
"\n                </p:Tp>\n"+
"\n                <p:Amt Ccy=\"EUR\">122.00</p:Amt>\n"+
"\n              </p:TaxAmt>\n"+
"\n              <p:AdjstmntAmtAndRsn>\n"+
"\n                <p:Amt Ccy=\"EUR\">10.0</p:Amt>\n"+
"\n                <p:CdtDbtInd>CRDT</p:CdtDbtInd>\n"+
"\n                <p:Rsn>1111</p:Rsn>\n"+
"\n                <p:AddtlInf>p:AddtlInf</p:AddtlInf>\n"+
"\n              </p:AdjstmntAmtAndRsn>\n"+
"\n              <p:RmtdAmt Ccy=\"EUR\">10.0</p:RmtdAmt>\n"+
"\n            </p:RfrdDocAmt>\n"+
"\n            <p:CdtrRefInf>\n"+
"\n              <p:Tp>\n"+
"\n                <p:CdOrPrtry>\n"+
"\n                  <p:Cd>RADM</p:Cd>\n"+
"\n                </p:CdOrPrtry>\n"+
"\n                <p:Issr>p:Issr</p:Issr>\n"+
"\n              </p:Tp>\n"+
"\n              <p:Ref>p:Ref</p:Ref>\n"+
"\n            </p:CdtrRefInf>\n"+
"\n            <p:Invcr>\n"+
"\n              <p:Nm>p:Nm</p:Nm>\n"+
"\n              <p:PstlAdr>\n"+
"\n                <p:AdrTp>ADDR</p:AdrTp>\n"+
"\n                <p:Dept>p:Dept</p:Dept>\n"+
"\n                <p:SubDept>p:SubDept</p:SubDept>\n"+
"\n                <p:StrtNm>Kingdom St</p:StrtNm>\n"+
"\n                <p:BldgNb>1</p:BldgNb>\n"+
"\n                <p:PstCd>560061</p:PstCd>\n"+
"\n                <p:TwnNm>Bengaluru</p:TwnNm>\n"+
"\n                <p:CtrySubDvsn>KA</p:CtrySubDvsn>\n"+
"\n                <p:Ctry>NL</p:Ctry>\n"+
"\n                <p:AdrLine>p:AdrLine</p:AdrLine>\n"+
"\n              </p:PstlAdr>\n"+
"\n              <p:Id>\n"+
"\n                <p:OrgId>\n"+
"\n                  <p:AnyBIC>AAAAAAZ9</p:AnyBIC>\n"+
"\n                  <p:Othr>\n"+
"\n                    <p:Id>p:Id</p:Id>\n"+
"\n                    <p:SchmeNm>\n"+
"\n                      <p:Cd>p:Cd</p:Cd>\n"+
"\n                    </p:SchmeNm>\n"+
"\n                    <p:Issr>p:Issr</p:Issr>\n"+
"\n                  </p:Othr>\n"+
"\n                </p:OrgId>\n"+
"\n              </p:Id>\n"+
"\n              <p:CtryOfRes>NL</p:CtryOfRes>\n"+
"\n              <p:CtctDtls>\n"+
"\n                <p:NmPrfx>DOCT</p:NmPrfx>\n"+
"\n                <p:Nm>p:Nm</p:Nm>\n"+
"\n                <p:PhneNb>+91-111111111111</p:PhneNb>\n"+
"\n                <p:MobNb>+91-111111111111</p:MobNb>\n"+
"\n                <p:FaxNb>+91-111111111111</p:FaxNb>\n"+
"\n                <p:EmailAdr>a@b.com</p:EmailAdr>\n"+
"\n                <p:Othr>p:Othr</p:Othr>\n"+
"\n              </p:CtctDtls>\n"+
"\n            </p:Invcr>\n"+
"\n            <p:Invcee>\n"+
"\n              <p:Nm>p:Nm</p:Nm>\n"+
"\n              <p:PstlAdr>\n"+
"\n                <p:AdrTp>ADDR</p:AdrTp>\n"+
"\n                <p:Dept>p:Dept</p:Dept>\n"+
"\n                <p:SubDept>p:SubDept</p:SubDept>\n"+
"\n                <p:StrtNm>Kingdom St</p:StrtNm>\n"+
"\n                <p:BldgNb>1</p:BldgNb>\n"+
"\n                <p:PstCd>560061</p:PstCd>\n"+
"\n                <p:TwnNm>Bengaluru</p:TwnNm>\n"+
"\n                <p:CtrySubDvsn>KA</p:CtrySubDvsn>\n"+
"\n                <p:Ctry>NL</p:Ctry>\n"+
"\n                <p:AdrLine>p:AdrLine</p:AdrLine>\n"+
"\n              </p:PstlAdr>\n"+
"\n              <p:Id>\n"+
"\n                <p:OrgId>\n"+
"\n                  <p:AnyBIC>AAAAAAZ9</p:AnyBIC>\n"+
"\n                  <p:Othr>\n"+
"\n                    <p:Id>p:Id</p:Id>\n"+
"\n                    <p:SchmeNm>\n"+
"\n                      <p:Cd>p:Cd</p:Cd>\n"+
"\n                    </p:SchmeNm>\n"+
"\n                    <p:Issr>p:Issr</p:Issr>\n"+
"\n                  </p:Othr>\n"+
"\n                </p:OrgId>\n"+
"\n              </p:Id>\n"+
"\n              <p:CtryOfRes>NL</p:CtryOfRes>\n"+
"\n              <p:CtctDtls>\n"+
"\n                <p:NmPrfx>DOCT</p:NmPrfx>\n"+
"\n                <p:Nm>p:Nm</p:Nm>\n"+
"\n                <p:PhneNb>+91-111111111111</p:PhneNb>\n"+
"\n                <p:MobNb>+91-111111111111</p:MobNb>\n"+
"\n                <p:FaxNb>+91-111111111111</p:FaxNb>\n"+
"\n                <p:EmailAdr>a@b.com</p:EmailAdr>\n"+
"\n                <p:Othr>p:Othr</p:Othr>\n"+
"\n              </p:CtctDtls>\n"+
"\n            </p:Invcee>\n"+
"\n            <p:TaxRmt>\n"+
"\n              <p:Cdtr>\n"+
"\n                <p:TaxId>p:TaxId</p:TaxId>\n"+
"\n                <p:RegnId>p:RegnId</p:RegnId>\n"+
"\n                <p:TaxTp>p:TaxTp</p:TaxTp>\n"+
"\n              </p:Cdtr>\n"+
"\n              <p:Dbtr>\n"+
"\n                <p:TaxId>p:TaxId</p:TaxId>\n"+
"\n                <p:RegnId>p:RegnId</p:RegnId>\n"+
"\n                <p:TaxTp>p:TaxTp</p:TaxTp>\n"+
"\n                <p:Authstn>\n"+
"\n                  <p:Titl>p:Titl</p:Titl>\n"+
"\n                  <p:Nm>p:Nm</p:Nm>\n"+
"\n                </p:Authstn>\n"+
"\n              </p:Dbtr>\n"+
"\n              <p:UltmtDbtr>\n"+
"\n                <p:TaxId>p:TaxId</p:TaxId>\n"+
"\n                <p:RegnId>p:RegnId</p:RegnId>\n"+
"\n                <p:TaxTp>p:TaxTp</p:TaxTp>\n"+
"\n                <p:Authstn>\n"+
"\n                  <p:Titl>p:Titl</p:Titl>\n"+
"\n                  <p:Nm>p:Nm</p:Nm>\n"+
"\n                </p:Authstn>\n"+
"\n              </p:UltmtDbtr>\n"+
"\n              <p:AdmstnZone>p:AdmstnZone</p:AdmstnZone>\n"+
"\n              <p:RefNb>p:RefNb</p:RefNb>\n"+
"\n              <p:Mtd>p:Mtd</p:Mtd>\n"+
"\n              <p:TtlTaxblBaseAmt Ccy=\"EUR\">10.0</p:TtlTaxblBaseAmt>\n"+
"\n              <p:TtlTaxAmt Ccy=\"EUR\">10.0</p:TtlTaxAmt>\n"+
"\n              <p:Dt>2016-06-24</p:Dt>\n"+
"\n              <p:SeqNb>0.0</p:SeqNb>\n"+
"\n              <p:Rcrd>\n"+
"\n                <p:Tp>p:Tp</p:Tp>\n"+
"\n                <p:Ctgy>p:Ctgy</p:Ctgy>\n"+
"\n                <p:CtgyDtls>p:CtgyDtls</p:CtgyDtls>\n"+
"\n                <p:DbtrSts>p:DbtrSts</p:DbtrSts>\n"+
"\n                <p:CertId>p:CertId</p:CertId>\n"+
"\n                <p:FrmsCd>p:FrmsCd</p:FrmsCd>\n"+
"\n                <p:Prd>\n"+
"\n                  <p:Yr>2016-06-24</p:Yr>\n"+
"\n                  <p:Tp>MM01</p:Tp>\n"+
"\n                  <p:FrToDt>\n"+
"\n                    <p:FrDt>2016-06-24</p:FrDt>\n"+
"\n                    <p:ToDt>2016-06-24</p:ToDt>\n"+
"\n                  </p:FrToDt>\n"+
"\n                </p:Prd>\n"+
"\n                <p:TaxAmt>\n"+
"\n                  <p:Rate>0.0</p:Rate>\n"+
"\n                  <p:TaxblBaseAmt Ccy=\"EUR\">10.0</p:TaxblBaseAmt>\n"+
"\n                  <p:TtlAmt Ccy=\"EUR\">122.00</p:TtlAmt>\n"+
"\n                  <p:Dtls>\n"+
"\n                    <p:Prd>\n"+
"\n                      <p:Yr>2016-06-24</p:Yr>\n"+
"\n                      <p:Tp>MM01</p:Tp>\n"+
"\n                      <p:FrToDt>\n"+
"\n                        <p:FrDt>2016-06-24</p:FrDt>\n"+
"\n                        <p:ToDt>2016-06-24</p:ToDt>\n"+
"\n                      </p:FrToDt>\n"+
"\n                    </p:Prd>\n"+
"\n                    <p:Amt Ccy=\"EUR\">10.0</p:Amt>\n"+
"\n                  </p:Dtls>\n"+
"\n                </p:TaxAmt>\n"+
"\n                <p:AddtlInf>p:AddtlInf</p:AddtlInf>\n"+
"\n              </p:Rcrd>\n"+
"\n            </p:TaxRmt>\n"+
"\n            <p:GrnshmtRmt>\n"+
"\n              <p:Tp>\n"+
"\n                <p:CdOrPrtry>\n"+
"\n                  <p:Cd>p:Cd</p:Cd>\n"+
"\n                </p:CdOrPrtry>\n"+
"\n                <p:Issr>p:Issr</p:Issr>\n"+
"\n              </p:Tp>\n"+
"\n              <p:Grnshee>\n"+
"\n                <p:Nm>p:Nm</p:Nm>\n"+
"\n                <p:PstlAdr>\n"+
"\n                  <p:AdrTp>ADDR</p:AdrTp>\n"+
"\n                  <p:Dept>p:Dept</p:Dept>\n"+
"\n                  <p:SubDept>p:SubDept</p:SubDept>\n"+
"\n                  <p:StrtNm>Kingdom St</p:StrtNm>\n"+
"\n                  <p:BldgNb>1</p:BldgNb>\n"+
"\n                  <p:PstCd>560061</p:PstCd>\n"+
"\n                  <p:TwnNm>Bengaluru</p:TwnNm>\n"+
"\n                  <p:CtrySubDvsn>KA</p:CtrySubDvsn>\n"+
"\n                  <p:Ctry>NL</p:Ctry>\n"+
"\n                  <p:AdrLine>p:AdrLine</p:AdrLine>\n"+
"\n                </p:PstlAdr>\n"+
"\n                <p:Id>\n"+
"\n                  <p:OrgId>\n"+
"\n                    <p:AnyBIC>AAAAAAZ9</p:AnyBIC>\n"+
"\n                    <p:Othr>\n"+
"\n                      <p:Id>p:Id</p:Id>\n"+
"\n                      <p:SchmeNm>\n"+
"\n                        <p:Cd>p:Cd</p:Cd>\n"+
"\n                      </p:SchmeNm>\n"+
"\n                      <p:Issr>p:Issr</p:Issr>\n"+
"\n                    </p:Othr>\n"+
"\n                  </p:OrgId>\n"+
"\n                </p:Id>\n"+
"\n                <p:CtryOfRes>NL</p:CtryOfRes>\n"+
"\n                <p:CtctDtls>\n"+
"\n                  <p:NmPrfx>MIST</p:NmPrfx>\n"+
"\n                  <p:Nm>ContactPersonName</p:Nm>\n"+
"\n                  <p:PhneNb>+91-111111111111</p:PhneNb>\n"+
"\n                  <p:MobNb>+91-111111111111</p:MobNb>\n"+
"\n                  <p:FaxNb>+91-111111111111</p:FaxNb>\n"+
"\n                  <p:EmailAdr>a@b.com</p:EmailAdr>\n"+
"\n                  <p:Othr>p:Othr</p:Othr>\n"+
"\n                </p:CtctDtls>\n"+
"\n              </p:Grnshee>\n"+
"\n              <p:GrnshmtAdmstr>\n"+
"\n                <p:Nm>GrnshmtAdmstrNm</p:Nm>\n"+
"\n                <p:PstlAdr>\n"+
"\n                  <p:AdrTp>ADDR</p:AdrTp>\n"+
"\n                  <p:Dept>p:Dept</p:Dept>\n"+
"\n                  <p:SubDept>p:SubDept</p:SubDept>\n"+
"\n                  <p:StrtNm>Kingdom St</p:StrtNm>\n"+
"\n                  <p:BldgNb>1</p:BldgNb>\n"+
"\n                  <p:PstCd>560061</p:PstCd>\n"+
"\n                  <p:TwnNm>Bengaluru</p:TwnNm>\n"+
"\n                  <p:CtrySubDvsn>KA</p:CtrySubDvsn>\n"+
"\n                  <p:Ctry>NL</p:Ctry>\n"+
"\n                  <p:AdrLine>p:AdrLine</p:AdrLine>\n"+
"\n                </p:PstlAdr>\n"+
"\n                <p:Id>\n"+
"\n                  <p:OrgId>\n"+
"\n                    <p:AnyBIC>AAAAAAZ9</p:AnyBIC>\n"+
"\n                    <p:Othr>\n"+
"\n                      <p:Id>p:Id</p:Id>\n"+
"\n                      <p:SchmeNm>\n"+
"\n                        <p:Cd>p:Cd</p:Cd>\n"+
"\n                      </p:SchmeNm>\n"+
"\n                      <p:Issr>p:Issr</p:Issr>\n"+
"\n                    </p:Othr>\n"+
"\n                  </p:OrgId>\n"+
"\n                </p:Id>\n"+
"\n                <p:CtryOfRes>NL</p:CtryOfRes>\n"+
"\n                <p:CtctDtls>\n"+
"\n                  <p:NmPrfx>DOCT</p:NmPrfx>\n"+
"\n                  <p:Nm>p:Nm</p:Nm>\n"+
"\n                  <p:PhneNb>+91-111111111111</p:PhneNb>\n"+
"\n                  <p:MobNb>+91-111111111111</p:MobNb>\n"+
"\n                  <p:FaxNb>+91-111111111111</p:FaxNb>\n"+
"\n                  <p:EmailAdr>a@b.com</p:EmailAdr>\n"+
"\n                  <p:Othr>p:Othr</p:Othr>\n"+
"\n                </p:CtctDtls>\n"+
"\n              </p:GrnshmtAdmstr>\n"+
"\n              <p:RefNb>p:RefNb</p:RefNb>\n"+
"\n              <p:Dt>2016-06-24</p:Dt>\n"+
"\n              <p:RmtdAmt Ccy=\"EUR\">{2}</p:RmtdAmt>\n"+
"\n              <p:FmlyMdclInsrncInd>true</p:FmlyMdclInsrncInd>\n"+
"\n              <p:MplyeeTermntnInd>true</p:MplyeeTermntnInd>\n"+
"\n            </p:GrnshmtRmt>\n"+
"\n            <p:AddtlRmtInf>p:AddtlRmtInf</p:AddtlRmtInf>\n"+
"\n          </p:Strd>\n"+
"\n        </p:RmtInf>\n"+
"\n    <p:SplmtryData>\n"+
"\n      <p:PlcAndNm>p:PlcAndNm</p:PlcAndNm>\n"+
"\n      <p:Envlp>\n"+
"\n        <ANY-ELEMENT/>\n"+
"\n      </p:Envlp>\n"+
"\n    </p:SplmtryData>\n"+
"\n      </p:DrctDbtTxInf>\n";

public static final String pmtInfo_footer = "</p:PmtInf>   \n";

public static final String footer = 
"\n    <p:SplmtryData>\n"+
"\n      <p:PlcAndNm>p:PlcAndNm</p:PlcAndNm>\n"+
"\n      <p:Envlp>\n"+
"\n        <ANY-ELEMENT/>\n"+
"\n      </p:Envlp>\n"+
"\n    </p:SplmtryData>\n"+
"\n  </p:CstmrDrctDbtInitn>\n"+
"</p:Document>";


}