public class InwardCreditTransferTemplate {

	public static final String InwardCTTemplateHeader = 
			  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
			+ "\n<S2SCTScf:SCTScfBlkCredTrf xsi:schemaLocation=\"urn:S2SCTScf:xsd:$SCTScfBlkCredTrf SCTScfBlkCredTrf.xsd\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:S2SCTScf=\"urn:S2SCTScf:xsd:$SCTScfBlkCredTrf\">"
			+ "\n<S2SCTScf:SndgInst>TRIONL2U</S2SCTScf:SndgInst>"
			+ "\n<S2SCTScf:RcvgInst>CCRIES2A</S2SCTScf:RcvgInst>"
			+ "\n<S2SCTScf:SrvcId>SCT</S2SCTScf:SrvcId>"
			+ "\n<S2SCTScf:TstCode>T</S2SCTScf:TstCode>"
			+ "\n<S2SCTScf:FType>SCF</S2SCTScf:FType>"
			+ "\n<S2SCTScf:FileRef>NSCT100629001366</S2SCTScf:FileRef>"
			+ "\n<S2SCTScf:RoutingInd>ALL</S2SCTScf:RoutingInd>"
			+ "\n<S2SCTScf:FileBusDt>{7}</S2SCTScf:FileBusDt>"
			+ "\n<S2SCTScf:FileCycleNo>01</S2SCTScf:FileCycleNo>"
			+ "\n<S2SCTScf:FIToFICstmrCdtTrf xmlns=\"urn:iso:std:iso:20022:tech:xsd:pacs.008.001.02\">"
			+ "\n<GrpHdr>"
			+ "\n		<MsgId>IncomingCT-{0}</MsgId>"
			+ "\n		<CreDtTm>{7}T15:41:10</CreDtTm>"
			+ "\n		<NbOfTxs>{8}</NbOfTxs>"
			+ "\n		<TtlIntrBkSttlmAmt Ccy=\"EUR\">{9}</TtlIntrBkSttlmAmt>"
			+ "\n		<IntrBkSttlmDt>{7}</IntrBkSttlmDt>"
			+ "\n				<SttlmInf>"
			+ "\n					<SttlmMtd>CLRG</SttlmMtd>"
			+ "\n					<ClrSys>"
			+ "\n						<Prtry>ST2</Prtry>"
			+ "\n					</ClrSys>"
			+ "\n				</SttlmInf>"
			+ "\n				<InstdAgt>"
			+ "\n					<FinInstnId>"
			+ "\n						<BIC>{13}</BIC>"
			+ "\n					</FinInstnId>"
			+ "\n				</InstdAgt>"
			+ "\n			</GrpHdr>";
	
	public static final String InwardCTTemplateBody = 
			  "\n			<CdtTrfTxInf>"
			+ "\n				<PmtId>"
			+ "\n					<InstrId>Instr-{0}-{1}</InstrId>"
			+ "\n					<EndToEndId>End-{0}-{1}</EndToEndId>"
			+ "\n					<TxId>TxId-{0}-{1}</TxId>"
			+ "\n				</PmtId>"
			+ "\n				<PmtTpInf>"
			+ "\n					<SvcLvl>"
			+ "\n						<Cd>SEPA</Cd>"
			+ "\n					</SvcLvl>"
			+ "\n				</PmtTpInf>"
			+ "\n				<IntrBkSttlmAmt Ccy=\"EUR\">{2}</IntrBkSttlmAmt>"
			+ "\n				<ChrgBr>SLEV</ChrgBr>"
			+ "\n				<InstgAgt>"
			+ "\n					<FinInstnId>"
			+ "\n						<BIC>LIKIGB2L</BIC>"
			+ "\n					</FinInstnId>"
			+ "\n				</InstgAgt>"
			+ "\n				<Dbtr>"
			+ "\n					<Nm>Arbind</Nm>"
			+ "\n					<PstlAdr>"
			+ "\n						<AdrLine>Indirizzo 1 Dbtr </AdrLine>"
			+ "\n						<AdrLine>Indirizzo 2 Dbtr </AdrLine>"
			+ "\n					</PstlAdr>"
			+ "\n					<Id>"
			+ "\n						<OrgId>"
			+ "\n							<BICOrBEI>AAAAAAAAAAA</BICOrBEI>"
			+ "\n						</OrgId>"
			+ "\n					</Id>"
			+ "\n				</Dbtr>"
			+ "\n				<DbtrAcct>"
			+ "\n					<Id>"
			+ "\n						<IBAN>{5}</IBAN>"
			+ "\n					</Id>"
			+ "\n				</DbtrAcct>"
			+ "\n				<DbtrAgt>"
			+ "\n					<FinInstnId>"
			+ "\n						<BIC>{13}</BIC>"
			+ "\n					</FinInstnId>"
			+ "\n				</DbtrAgt>"
			+ "\n				<CdtrAgt>"
			+ "\n					<FinInstnId>"
			+ "\n						<BIC>{13}</BIC>"
			+ "\n					</FinInstnId>"
			+ "\n				</CdtrAgt>"
			+ "\n				<Cdtr>"
			+ "\n					<Nm>Avinash</Nm>"
			+ "\n					<PstlAdr>"
			+ "\n						<AdrLine>indirizzo 1 Cdtr</AdrLine>"
			+ "\n						<AdrLine>indirizzo 2 Cdtr</AdrLine>"
			+ "\n					</PstlAdr>"
			+ "\n					<Id>"
			+ "\n						<OrgId>"
			+ "\n							<BICOrBEI>AAAAAAAAAAA</BICOrBEI>"
			+ "\n						</OrgId>"
			+ "\n					</Id>"
			+ "\n				</Cdtr>"
			+ "\n				<CdtrAcct>"
			+ "\n					<Id>"
			+ "\n						<IBAN>{3}</IBAN>"
			+ "\n					</Id>"
			+ "\n				</CdtrAcct>"
			+ "\n				<RmtInf>"
			+ "\n					<Ustrd>String</Ustrd>"
			+ "\n				</RmtInf>"
			+ "\n			</CdtTrfTxInf>";
	
	public static final String InwardCTTemplateFooter =

              "\n		</S2SCTScf:FIToFICstmrCdtTrf>"
			+ "\n	</S2SCTScf:SCTScfBlkCredTrf>"	;

}
