public class MandateTemplate {

	public static final String MandateHeaderTemplate = 
			
					  "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
					+ "\n	<urn:Document xmlns:urn=\"urn:iso:std:iso:20022:tech:xsd:pain.009.001.04MPM\">"
					+ "\n		<urn:MndtInitnReq>"
					+ "\n			<urn:GrpHdr>"
					+ "\n				<urn:MsgId>MsgId-{0}</urn:MsgId>"
					+ "\n				<urn:CreDtTm>{7}T13:17:20</urn:CreDtTm>"
					+ "\n			</urn:GrpHdr>";
	
	
	public static final String MandateItemTemplate =
					  "\n			<urn:Mndt>"
					+ "\n				<urn:MndtId>MndtId-{0}-{1}</urn:MndtId>"
					+ "\n				<urn:MndtReqId>MndtReqId-{0}-{1}</urn:MndtReqId>"
					+ "\n				<urn:Ocrncs>"
					+ "\n					<urn:SeqTp>RCUR</urn:SeqTp>"
					+ "\n					<urn:Frqcy>"
					+ "\n						<urn:Tp>YEAR</urn:Tp>"
					+ "\n					</urn:Frqcy>"
					+ "\n					<urn:Drtn>"
					+ "\n						<urn:FrDt>2014-05-04</urn:FrDt>"
					+ "\n						<urn:ToDt>2020-05-04</urn:ToDt>"
					+ "\n					</urn:Drtn>"
					+ "\n				</urn:Ocrncs>"
					+ "\n				<urn:ColltnAmt Ccy=\"EUR\">500.00</urn:ColltnAmt>"
					+ "\n				<urn:Cdtr>"
					+ "\n					<urn:Nm>Mr Creditor</urn:Nm>"
					+ "\n				</urn:Cdtr>"
					+ "\n				<urn:CdtrAcct>"
					+ "\n					<urn:Id>"
					+ "\n						<urn:IBAN>{14}</urn:IBAN>"
					+ "\n					</urn:Id>"
					+ "\n				</urn:CdtrAcct>"
					+ "\n				<urn:CdtrAgt>"
					+ "\n					<urn:FinInstnId>"
					+ "\n						<urn:ClrSysMmbId>"
					+ "\n							<urn:MmbId>ClrSysID-01</urn:MmbId>"
					+ "\n						</urn:ClrSysMmbId>"
					+ "\n						<urn:Nm>ClrSysName1</urn:Nm>"
					+ "\n					</urn:FinInstnId>"
					+ "\n				</urn:CdtrAgt>"
					+ "\n				<urn:Dbtr>"
					+ "\n					<urn:Nm>Mr Debtor</urn:Nm>"
					+ "\n				</urn:Dbtr>"
					+ "\n				<urn:DbtrAcct>"
					+ "\n					<urn:Id>"
					+ "\n						<urn:IBAN>{14}</urn:IBAN>"
					+ "\n					</urn:Id>"
					+ "\n				</urn:DbtrAcct>"
					+ "\n				<urn:DbtrAgt>"
					+ "\n					<urn:FinInstnId>"
					+ "\n						<urn:ClrSysMmbId>"
					+ "\n							<urn:MmbId>ClrSysID-02</urn:MmbId>"
					+ "\n						</urn:ClrSysMmbId>"
					+ "\n						<urn:Nm>ClrSysName1</urn:Nm>"
					+ "\n					</urn:FinInstnId>"
					+ "\n				</urn:DbtrAgt>"
					+ "\n				<urn:UsrDfndFlds>"
					+ "\n					<urn:UsrDfndFld>"
					+ "\n						<urn:name>HostID</urn:name>"
					+ "\n						<urn:value>MPM</urn:value>"
					+ "\n					</urn:UsrDfndFld>"
					+ "\n					<urn:UsrDfndFld>"
					+ "\n						<urn:name>Network</urn:name>"
					+ "\n						<urn:value>STEP2</urn:value>"
					+ "\n					</urn:UsrDfndFld>"
					+ "\n					<urn:UsrDfndFld>"
					+ "\n						<urn:name>MandateGroupID</urn:name>"
					+ "\n						<urn:value>{17}</urn:value>"
					+ "\n					</urn:UsrDfndFld>"
					+ "\n					<urn:UsrDfndFld>"
					+ "\n						<urn:name>MandateType</urn:name>"
					+ "\n						<urn:value>{15}</urn:value>"
					+ "\n					</urn:UsrDfndFld>"
					+ "\n				</urn:UsrDfndFlds>"
					+ "\n			</urn:Mndt>";
	
	public static final String MandateFooterTemplate =
					  "\n		</urn:MndtInitnReq>"
					+ "\n	</urn:Document>";

}
