
package ub_r_cb_acc_retrieveaccountmovements_srvws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UB_R_CB_ACC_RetrieveAccountMovements_SRVWSService", targetNamespace = "http://UB_R_CB_ACC_RetrieveAccountMovements_SRVWS", wsdlLocation = "http://blrl10tl5y2:9083/bfweb/services/UB_R_CB_ACC_RetrieveAccountMovements_SRVWS?wsdl")
public class UBRCBACCRetrieveAccountMovementsSRVWSService
    extends Service
{

    private final static URL UBRCBACCRETRIEVEACCOUNTMOVEMENTSSRVWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException UBRCBACCRETRIEVEACCOUNTMOVEMENTSSRVWSSERVICE_EXCEPTION;
    private final static QName UBRCBACCRETRIEVEACCOUNTMOVEMENTSSRVWSSERVICE_QNAME = new QName("http://UB_R_CB_ACC_RetrieveAccountMovements_SRVWS", "UB_R_CB_ACC_RetrieveAccountMovements_SRVWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://blrl10tl5y2:9083/bfweb/services/UB_R_CB_ACC_RetrieveAccountMovements_SRVWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UBRCBACCRETRIEVEACCOUNTMOVEMENTSSRVWSSERVICE_WSDL_LOCATION = url;
        UBRCBACCRETRIEVEACCOUNTMOVEMENTSSRVWSSERVICE_EXCEPTION = e;
    }

    public UBRCBACCRetrieveAccountMovementsSRVWSService() {
        super(__getWsdlLocation(), UBRCBACCRETRIEVEACCOUNTMOVEMENTSSRVWSSERVICE_QNAME);
    }

    public UBRCBACCRetrieveAccountMovementsSRVWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UBRCBACCRETRIEVEACCOUNTMOVEMENTSSRVWSSERVICE_QNAME, features);
    }

    public UBRCBACCRetrieveAccountMovementsSRVWSService(URL wsdlLocation) {
        super(wsdlLocation, UBRCBACCRETRIEVEACCOUNTMOVEMENTSSRVWSSERVICE_QNAME);
    }

    public UBRCBACCRetrieveAccountMovementsSRVWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UBRCBACCRETRIEVEACCOUNTMOVEMENTSSRVWSSERVICE_QNAME, features);
    }

    public UBRCBACCRetrieveAccountMovementsSRVWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UBRCBACCRetrieveAccountMovementsSRVWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UBRCBACCRetrieveAccountMovementsSRVWSPortType
     */
    @WebEndpoint(name = "UB_R_CB_ACC_RetrieveAccountMovements_SRVWSPort")
    public UBRCBACCRetrieveAccountMovementsSRVWSPortType getUBRCBACCRetrieveAccountMovementsSRVWSPort() {
        return super.getPort(new QName("http://UB_R_CB_ACC_RetrieveAccountMovements_SRVWS", "UB_R_CB_ACC_RetrieveAccountMovements_SRVWSPort"), UBRCBACCRetrieveAccountMovementsSRVWSPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UBRCBACCRetrieveAccountMovementsSRVWSPortType
     */
    @WebEndpoint(name = "UB_R_CB_ACC_RetrieveAccountMovements_SRVWSPort")
    public UBRCBACCRetrieveAccountMovementsSRVWSPortType getUBRCBACCRetrieveAccountMovementsSRVWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://UB_R_CB_ACC_RetrieveAccountMovements_SRVWS", "UB_R_CB_ACC_RetrieveAccountMovements_SRVWSPort"), UBRCBACCRetrieveAccountMovementsSRVWSPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UBRCBACCRETRIEVEACCOUNTMOVEMENTSSRVWSSERVICE_EXCEPTION!= null) {
            throw UBRCBACCRETRIEVEACCOUNTMOVEMENTSSRVWSSERVICE_EXCEPTION;
        }
        return UBRCBACCRETRIEVEACCOUNTMOVEMENTSSRVWSSERVICE_WSDL_LOCATION;
    }

}
