
package ub_r_cb_acc_retrieveaccountmovements_srvws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.trapedza.bankfusion.webservices.Bfgenericsoapheader;
import com.trapedza.bankfusion.webservices.UBRCBACCRetrieveAccountMovementsSRVRequestType;
import com.trapedza.bankfusion.webservices.UBRCBACCRetrieveAccountMovementsSRVResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UB_R_CB_ACC_RetrieveAccountMovements_SRVWSPortType", targetNamespace = "http://UB_R_CB_ACC_RetrieveAccountMovements_SRVWS")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.misys.bankfusion.attributes.ObjectFactory.class,
    com.misys.bf.attributes.ObjectFactory.class,
    com.misys.cbs.msgs.v1r0.ObjectFactory.class,
    com.misys.cbs.types.ObjectFactory.class,
    com.misys.cbs.types.header.ObjectFactory.class,
    com.trapedza.bankfusion.webservices.ObjectFactory.class
})
public interface UBRCBACCRetrieveAccountMovementsSRVWSPortType {


    /**
     * 
     * @param bfgenericsoapheader
     * @param ubRCBACCRetrieveAccountMovementsSRVRequest
     * @return
     *     returns com.trapedza.bankfusion.webservices.UBRCBACCRetrieveAccountMovementsSRVResponseType
     */
    @WebMethod(operationName = "UB_R_CB_ACC_RetrieveAccountMovements_SRV", action = "http://UB_R_CB_ACC_RetrieveAccountMovements_SRVWS/UB_R_CB_ACC_RetrieveAccountMovements_SRVWSPortType/UB_R_CB_ACC_RetrieveAccountMovements_SRVRequest")
    @WebResult(name = "UB_R_CB_ACC_RetrieveAccountMovements_SRVResponse", targetNamespace = "http://webservices.bankfusion.trapedza.com", partName = "UB_R_CB_ACC_RetrieveAccountMovements_SRVResponse")
    public UBRCBACCRetrieveAccountMovementsSRVResponseType ubRCBACCRetrieveAccountMovementsSRV(
        @WebParam(name = "UB_R_CB_ACC_RetrieveAccountMovements_SRVRequest", targetNamespace = "http://webservices.bankfusion.trapedza.com", partName = "UB_R_CB_ACC_RetrieveAccountMovements_SRVRequest")
        UBRCBACCRetrieveAccountMovementsSRVRequestType ubRCBACCRetrieveAccountMovementsSRVRequest,
        @WebParam(name = "bfgenericsoapheader", targetNamespace = "http://webservices.bankfusion.trapedza.com", header = true, partName = "bfgenericsoapheader")
        Bfgenericsoapheader bfgenericsoapheader);

}
