
package com.trapedza.bankfusion.webservices.security;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LoginSerivce", targetNamespace = "http://security.webservices.bankfusion.trapedza.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.misys.bf.attributes.ObjectFactory.class,
    com.trapedza.bankfusion.webservices.security.ObjectFactory.class
})
public interface LoginSerivce {


    /**
     * 
     * @param request
     * @param applicationID
     * @param passCode
     * @param userName
     * @param osUserID
     * @param password
     * @return
     *     returns com.trapedza.bankfusion.webservices.security.LoginResponseType
     */
    @WebMethod(action = "urn:login")
    @WebResult(name = "response", targetNamespace = "http://security.webservices.bankfusion.trapedza.com", partName = "response")
    public LoginResponseType login(
        @WebParam(name = "password", targetNamespace = "http://security.webservices.bankfusion.trapedza.com", header = true, partName = "password")
        Password password,
        @WebParam(name = "userName", targetNamespace = "http://security.webservices.bankfusion.trapedza.com", header = true, partName = "userName")
        UserName userName,
        @WebParam(name = "passCode", targetNamespace = "http://security.webservices.bankfusion.trapedza.com", header = true, partName = "passCode")
        PassCode passCode,
        @WebParam(name = "OSUserID", targetNamespace = "http://security.webservices.bankfusion.trapedza.com", header = true, partName = "OSUserID")
        OSUserID osUserID,
        @WebParam(name = "ApplicationID", targetNamespace = "http://security.webservices.bankfusion.trapedza.com", header = true, partName = "ApplicationID")
        ApplicationID applicationID,
        @WebParam(name = "request", targetNamespace = "http://security.webservices.bankfusion.trapedza.com", partName = "request")
        Request request);

}
