mklink /j D:\Payments\INSTALL-LOCATION\FBE429\BankFusion\SYMBOLIC D:\Payments\INSTALL-LOCATION\FBE429\BankFusion\INSTALL\4.2.9.1.45
mklink /j D:\Payments\INSTALL-LOCATION\FBE429\CBS\SYMBOLIC D:\Payments\INSTALL-LOCATION\FBE429\CBS\INSTALL\4.2.9.1.31
mklink /j D:\Payments\INSTALL-LOCATION\FBE429\BFAM\SYMBOLIC D:\Payments\INSTALL-LOCATION\FBE429\BFAM\INSTALL\4.2.9.1.31
mklink /j D:\Payments\INSTALL-LOCATION\FBE429\BFPM\SYMBOLIC D:\Payments\INSTALL-LOCATION\FBE429\BFPM\INSTALL\4.2.9.1.31
mklink /j D:\Payments\INSTALL-LOCATION\FBE429\BFAO\SYMBOLIC D:\Payments\INSTALL-LOCATION\FBE429\BFAO\INSTALL\4.2.9.1.31
mklink /j D:\Payments\INSTALL-LOCATION\FBE429\WIF\SYMBOLIC D:\Payments\INSTALL-LOCATION\FBE429\WIF\INSTALL\4.2.9.1.31
mklink /j D:\Payments\INSTALL-LOCATION\FBE429\UniversalBanking\SYMBOLIC D:\Payments\INSTALL-LOCATION\FBE429\UniversalBanking\INSTALL\4.2.9.1.102
mklink /j D:\Payments\INSTALL-LOCATION\FBE429\Party\SYMBOLIC D:\Payments\INSTALL-LOCATION\FBE429\Party\INSTALL\4.2.9.1.14
mklink /j D:\Payments\INSTALL-LOCATION\FBE429\BFBT\SYMBOLIC D:\Payments\INSTALL-LOCATION\FBE429\BFBT\INSTALL\4.2.9.1.27
exit
